### ISSUE TITLE
When you change the framework contents, you have to edit BUILD.gn

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#102]
_From @Hixie on May 19, 2015 22:45_

The BUILD.gn file should automatically figure out what to package from the framework, so that you don't have to both change the framework and update the BUILD.gn file for each new file.

@johnmccutchan @eseidelGoogle

_Copied from original issue: domokit/mojo#171_

**Comment by abarth** [comment]
You don't have to edit BUILD.gn anymore.
