### ISSUE TITLE
Popup menus don't clip their contents when shrinking

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#103]
_From @Hixie on May 12, 2015 19:33_

When the popup menu shrinks after being dismissed, the contents overflow out of the shrinking box.

_Copied from original issue: domokit/mojo#164_

**Comment by Hixie** [comment]
_From @abarth on June 11, 2015 19:49_

Does this issue occur in stocks2?

**Comment by abarth** [comment]
I believe I fixed this issue.
