### ISSUE TITLE
Popup menus require too much boilerplate

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#107]
_From @Hixie on May 12, 2015 19:24_

The PopupMenu (popup_menu.dart) and PopupMenuItem (popup_menu_item) widgets require a ton of boilerplate to use correctly today. They should just trivially work if you just construct a menu and trigger it from some button (and indeed there should probably just be a menu button that knows how to trigger a menu so you don't even need that).

_Copied from original issue: domokit/mojo#160_

**Comment by abarth** [comment]
This is much better now that we have `showMenu`
