### ISSUE TITLE
Popup menus don't tell you when they were clicked

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#108]
_From @Hixie on May 12, 2015 19:23_

The PopupMenu (popup_menu.dart) and PopupMenuItem (popup_menu_item) widgets don't tell you when they've been picked.

_Copied from original issue: domokit/mojo#159_

**Comment by Hixie** [comment]
And in particular, since you don't build the PopupMenuItem directly, you have no way to listen to the onGestureTap event on the whole popup menu item.

**Comment by abarth** [comment]
Now `showMenu` returns the value that was selected.
