### ISSUE TITLE
Dismissable widgets can be dismissed too easily

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1098]
Please make them harder to dismiss and/or maybe have it configurable.

**Comment by HansMuller** [comment]
There are some scrolling configuration parameters that I think could be applied to Dismissable and PageableList. In fact we may need to apply them to Scrollable too.

getTapTimeout()
getTouchSlop()
For PageableList - getScaledPagingTouchSlop()

For the Android definitions see:
https://github.com/android/platform_frameworks_base/blob/master/core/java/android/view/ViewConfiguration.java

The Sky versions defined are in sky/packages/sky/lib/gestures/constants.dart,
