### ISSUE TITLE
Implement selection widget, a.k.a. dropdown buttons

### ISSUE THREAD

**Issue by mishadynin** [flutter/engine#1113]
Material design spec at  https://www.google.com/design/spec/components/buttons.html#buttons-other-buttons calls them 'Mobile dropdown buttons'.

Workaround: use popup menus.

**Comment by Hixie** [comment]
I'm planning on exposing a "showPopupMenu()" method soon which should make it much easier to implement this, FWIW.

**Comment by abarth** [comment]
showPopupMenu exists.  We're still missing a widget that does this properly.

**Comment by mishadynin** [comment]
Unfortunately popup menus (and thus a hand-rolled selection widget) do not support scrolling if there are too many items, which is a common use case for selection.

**Comment by abarth** [comment]
PopupMenu should scroll.  It's got a ScrollableViewport in there.

**Comment by HansMuller** [comment]
I will create Material Design mobile dropdown buttons. Hopefully they can be based on PopupMenu.

**Comment by abarth** [comment]
I think @HansMuller did this in a4147ee22cdfdb19f767ff40066c158c9ae1a990
