### ISSUE TITLE
Link to examples, from sky's sdk README, is 404

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#114]
_From @sethladd on May 8, 2015 1:29_

From https://github.com/domokit/mojo/tree/master/sky/sdk#examples

Click the link "examples directory"

Expected: a view of the examples directory

Actual: 404

_Copied from original issue: domokit/mojo#153_

**Comment by Hixie** [comment]
_From @MitchRudominer on May 8, 2015 1:37_

I see the examples directory when I click on the link.

**Comment by Hixie** [comment]
_From @sethladd on May 8, 2015 2:45_

Hm. Go to https://github.com/domokit/mojo/tree/master/sky/sdk

Then, find "For examples, please see the examples directory."

Clicking on "examples directory" links me to https://github.com/domokit/mojo/blob/master/sky/sdk/examples which is a 404 for me.

**Comment by Hixie** [comment]
_From @MitchRudominer on May 8, 2015 4:32_

Sorry, you are right. I get a 404 too.

**Comment by abarth** [comment]
These aren't 404s anymore.
