### ISSUE TITLE
sky_tool should be able to make a skyx

### ISSUE THREAD

**Issue by jamesr** [flutter/engine#1149]

**Comment by abarth** [comment]
/cc @iansf 

We have everything in place to do this.  I believe Ian is planning to make this work as part of #983

**Comment by iansf** [comment]
That's correct.  I suspect that I should be able to leverage some of the work that @mpcomplete has been doing on updating for this as well, but right now my main task is to get sky_tool fully into dart.

**Comment by abarth** [comment]
I can take a look at this.

**Comment by abarth** [comment]
The code for making skyx files is not in sky_tools (as the build command).  We still need to download sky_snapshot, which @jamesr is working on.

**Comment by jamesr** [comment]
"sky_tool build" now emits an app.flx when run on a linux host.
