### ISSUE TITLE
The Anchor feature in TransitionBase is broken

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1163]
It can't handle the same Anchor being passed to multiple transitions.
It can't handle a transition's `anchor` being changed during a secondary build.

**Comment by Hixie** [comment]
One possibility is to have it use GlobalKeys to track the transition.

Another is to have a TransitionBuilder helper object that you instantiate and then use to build anywhere you want that particular transition. It would own its performance, but would be able to create multiple transitions that all use the same logic. This would also remove the need for buildWithChild().

**Comment by Hixie** [comment]
I think the builder approach is probably the way to go.

**Comment by Hixie** [comment]
Actually we don't even need a class for this. Anyone who would take an anchor can just expose a transition builder method that takes a child and returns something prebuilt.

**Comment by Hixie** [comment]
...except you can't easily get a hold of that object from a build() method... Hmm...

**Comment by abarth** [comment]
`Anchor` no longer exists.
