### ISSUE TITLE
Sky UI is "invisible" on a Nexus 6

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#117]
_From @tonygentilcore on April 30, 2015 23:19_

I'm building a sky app in mojo shell that runs fine on the Nexus 5, 7, 10 and GWatch. But on the Nexus 6, the same code renders the initial background color but nothing else. If I interact with the UI, where the elements should be, I can see print statements being hit indicating that the UI is fully interactive and working (eg. I can tap buttons, but the screen just stays a solid color).

adb logcat doesn't show any errors or crashes, but I can give repo instructions offline if anyone is interested.

/cc @MitchRudominer @eseidel

_Copied from original issue: domokit/mojo#135_

**Comment by Hixie** [comment]
_From @eseidelGoogle on May 4, 2015 17:56_

Are you using mojo_shell or SkyShell?

https://skia.googlesource.com/skia/+/a8fcea0cd09080de45143f2726059398cd8b8049
was supposed to fix this for mojo_shell (and did at the time).

Basically there is a bug in the N6 GPU which skia knows how to work around assuming we initialize it right. We had it working in mojo_shell, I've not tried SkyShell.

**Comment by Hixie** [comment]
_From @tonygentilcore on May 4, 2015 18:1_

This was a mojo_shell built at ToT on Thursday. @MitchRudominer has the device to repro it, I was just helping to get his dev environment set up when we stumbled upon it.

**Comment by Hixie** [comment]
_From @MitchRudominer on May 5, 2015 1:34_

Using ToT from just now (Monday evening) I'm getting:
 ./sky/tools/skydb start  out/android_Debug sky/examples/raw/touch-demo.sky
* Works fine when I plug in a Nexus 5
* When I plug in a Nexus 6 I get first a white screen, then a blue screen, then a white screen but no text and no response to touch. I don't notice anything obvious in logcat output.

Sky app downloaded from the Play Store works fine. Sky SDK from separate repo created for Dart Summit works fine.

**Comment by Hixie** [comment]
_From @MitchRudominer on May 5, 2015 18:23_

Not sure if there is anything useful in it but here is a link to output from "adb logcat". Let me know if the link (to my Google Drive) does not work for you.
https://drive.google.com/a/google.com/file/d/0B31bRQY0wi60d194dGNWb1lxYU0/view?usp=sharing

**Comment by Hixie** [comment]
_From @jamesr on May 6, 2015 23:55_

This is looking like a skia/ganesh issue of some sort.  The issue we're seeing in ganesh_app (which uses ganesh to draw into a texture and then swaps that on screen) is that if we tell Skia to clear or draw rectangles everything shows up fine, but if we ask ganesh to draw anti-aliased circles/ovals/rounded rectangles/DRRects then the draw call appears to vanish.  I've captured the shader program ganesh is using for drawing an antialiased circle:

// vertex

#version 100
uniform mediump vec4 urtAdjustment_Stage0;
attribute mediump vec2 inPosition;
attribute mediump vec4 inCircleEdge;
varying mediump vec4 vCircleEdge_Stage0;
void main() 
{
	vCircleEdge_Stage0 = inCircleEdge;
	vec2 pos2 = inPosition;
	gl_Position = vec4(pos2.x * urtAdjustment_Stage0.x + urtAdjustment_Stage0.y, pos2.y * urtAdjustment_Stage0.z + urtAdjustment_Stage0.w, 0, 1);
	gl_PointSize = 1.0;
}


// fragment

#version 100
precision mediump float;
uniform mediump vec4 uColor_Stage0;
varying mediump vec4 vCircleEdge_Stage0;
void main() 
{
	vec4 outputColor_Stage0;
	vec4 outputCoverage_Stage0;
	{
		// Stage 0, CircleEdge
		outputColor_Stage0 = uColor_Stage0;
		float d = length(vCircleEdge_Stage0.xy);
		float edgeAlpha = clamp(vCircleEdge_Stage0.z * (1.0 - d), 0.0, 1.0);
		outputCoverage_Stage0 = vec4(edgeAlpha);
	}
	{
		// Xfer Processor: Porter Duff
		gl_FragColor = outputColor_Stage0 * outputCoverage_Stage0;
	}
}

and can draw using it in a standalone mojo app just fine on this device.

I'll look next at whether ganesh switches draw targets, maybe it's trying to use an MSAA framebuffer and failing to resolve it or there's some ordering issue.

**Comment by Hixie** [comment]
_From @jamesr on May 7, 2015 0:14_

adding an explicit glFlush() after the SkCanvas::drawCircle() call makes ganesh_app draw again.  So does forcing workarounds().unbind_attachments_on_bound_render_fbo_delete to true inside gles2_cmd_decoder.  Looking into why it's not set for us..

**Comment by Hixie** [comment]
_From @jamesr on May 7, 2015 0:18_

In chrome a bunch of bits are being set in content/browser/gpu/gpu_data_manager_impl_private.cc.  We don't have or run any code like that in Mojo.  One of the things it does is make GPU driver workaround decisions, roughly here in the code:

https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/gpu/gpu_data_manager_impl_private.cc&sq=package:chromium&type=cs&l=562&rcl=1430942692

**Comment by cdotstout** [comment]
Should be resolved

**Comment by abarth** [comment]
Yep.
