### ISSUE TITLE
The tests are absurdly slow

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1172]
The tests take too long to run. I don't understand why; they should take mere milliseconds.

**Comment by abarth** [comment]
How long do they take to run on your machine?

**Comment by Hixie** [comment]
43s wall-clock (1m18s user, presumably across two CPUs?).
For comparison, the analyzer takes 6 seconds (which is also too long).

**Comment by abarth** [comment]
Sounds like the same issue @apwilson was having with the test harness crawling symlinks.

**Comment by Hixie** [comment]
yeah, though i wasn't able to figure out which version of the test package it's using so i could change it. :-/

**Comment by Hixie** [comment]
Oh hey I did a gclient sync and now it does pick up my hacked copy of test. Now it runs in 6 seconds!

**Comment by apwilson** [comment]
Awesome!

Just for reference, the workaround is this:  https://github.com/apwilson/test/commit/368cf30a5d154d971dba72302f8c3b32a83b2ae7

**Comment by apwilson** [comment]
And for reasons why dart/test don't want to implement that fix, see: https://github.com/dart-lang/test/issues/337
