### ISSUE TITLE
Consider calling didMount() before build() for StatefulComponents

### ISSUE THREAD

**Issue by abarth** [flutter/engine#1173]
Currently, we build first and then call didMount.  That makes the state machine for StatefulComponents really complex.  For example, if you get unmounted, you can be asked to build before you're remounted.  If you draw out the state machine, it's much cleaner if didMount comes before build and didUnmount is always followed by didMount before build.  That gives you the invariant that you only ever build while mounted.

/cc @Hixie

**Comment by Hixie** [comment]
It's possible to be built without being mounted ever (e.g. the MixedViewport widget does it to its children).

**Comment by abarth** [comment]
The state machine for stateful components is a lot more rational now that we have fn3.
