### ISSUE TITLE
Click doesn't work on mojo_shell on Linux

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1189]
(This is using `mojo_run`.) When I use my mouse to click, it seems to be interpreted as a `pointer down`. When I click again, I get a `pointer up` at the new mouse position.

I know that `sky_viewer.mojo` is not likely to be supported for Desktop, but this issue could extend to mobile as well. I have not yet tested whether a mouse attached to a phone will have the same behavior.

**Comment by afandria** [comment]
I tried attaching a mouse to my Nexus 5 (running with sky shell). Clicking feels normal, so I don't think there's a problem for mobile.

**Comment by j9brown** [comment]
Known issue.  I am working on it.

**Comment by abarth** [comment]
@j9brown fixed this issue.
