### ISSUE TITLE
Text wrapping for really long words is weird.

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1190]
If I have a super long line with no whitespace wrapping seems to make a new line for every character that doesn't fit on the last line.  Like this:

r
e
a
l
l
y
l
onglinethatneedstowrap

**Comment by afandria** [comment]
Agreed, I saw this too.

**Comment by apwilson** [comment]
The behaviour now seems to be to not wrap at all.

**Comment by turu** [comment]
See #1155 as well.

**Comment by apwilson** [comment]
This is still an issue.
