### ISSUE TITLE
Debugging tests is unnecessarily hard

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1196]
It would be great if there was a way to launch a single test in Observatory. Right now since there's no way to set breakpoints before you've loaded the code, the only way I can think to do it is to modify the code to call debugger(), then run the test, then attach the debugger (somewhere? it's not clear where to attach it, really). Really I want the equivalent of "start with gdb" but for observatory.

**Comment by sethladd** [comment]
cc @devoncarew as we're exploring a debugger

Would make a ton of sense to right-click on a single test and run that, with the debugger, from Atom
