### ISSUE TITLE
Menu items don't always splash when tapped

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#120]
_From @Hixie on April 21, 2015 22:20_

Sometimes, I haven't worked out when, if you pop open a menu and then tap an item, it doesn't get a material splash. Other times it does.

_Copied from original issue: domokit/mojo#114_

**Comment by Hixie** [comment]
_From @abarth on June 13, 2015 17:20_

Does this issue still occur in stocks2?

**Comment by abarth** [comment]
Seems to be fixed.  Please re-open if you can still reproduce the issue.
