### ISSUE TITLE
A child's Opacity parent shouldn't be hit if the child hasn't been hit.

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1221]
One example of this is wrapping a Circle with an Opacity.  The Circle has a circular hit region while the Opacity has a square hit region that currently could be hit in the corners around the Circle.

Instead of the Opacity being hit in those cases, whatever is behind the Circle should be hit.

**Comment by krisgiesing** [comment]
Where are you attaching the listener in this example?

**Comment by Hixie** [comment]
LIstener wrapping Opacity wrapping Circle.

**Comment by apwilson** [comment]
This currently isn't blocking for Pink Sky.
