### ISSUE TITLE
Entering immersive corrupts part of the screen for a frame due to GL context size mismatch

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1227]
It's hard to explain better than that but I've a video I can share offline.

**Comment by apwilson** [comment]
Upon further inspection of my video I believe this is due to a resize that takes place shortly after launch due to immersive mode being enabled.

**Comment by Hixie** [comment]
cc @chinmaygarde @abarth

**Comment by apwilson** [comment]
Is there anything I can do on my side to prevent the glitch?

**Comment by abarth** [comment]
I don't think there's any way to work around the issue on your side.  We just need to size the GL context correctly in C++.
