### ISSUE TITLE
How use sky_engine communicate with java or c++, Is there some guide? 

### ISSUE THREAD

**Issue by tain335** [flutter/engine#1230]
How use sky_engine communicate with java or c++, Is there some guide? 
Can use webstrom debug sky app?

**Comment by abarth** [comment]
We use Mojo to communicate between C++, Java, and Dart: https://github.com/domokit/mojo

Unfortunately, there isn't a particularly good guide to this part of the system yet.

**Comment by abarth** [comment]
Mojo needs much better documentation, but that's really an issue for https://github.com/domokit/mojo ...
