### ISSUE TITLE
Tutorial is out of date

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/engine#1236]
The tutorial is out of date and needs to be updated.

Under "Listening to Events":
- onGestureTap is not a ctor parameter of Listener
- start is not a ctor parameter of BoxDecoration
- LinearGradient is defined not in 'package:sky/widgets.dart'
- GestureDetector is not mentioned

Also, maybe it would help if the examples in the tutorial were included in the "examples" directory so that dartanalyzer could catch these problems.

**Comment by abarth** [comment]
Thanks!

**Comment by abarth** [comment]
I fixed the issues you mentioned, but you're right that we need a better process for maintaining these examples so they don't get out of date...
