### ISSUE TITLE
Nested Stack fails in checked mode

### ISSUE THREAD

**Issue by turu** [flutter/engine#1252]
**Steps to reproduce:**
**1.** Create a widget tree containing a ```Container``` with a ```Stack``` of some widgets ```Positioned``` relative to the ```Container```, placed in a ```Positioned```, on a ```Stack``` :
Example: 
```Dart
class NestedStacksApp extends App {
  @override
  Widget build() {
    return new Container(
        decoration: new BoxDecoration(backgroundColor: RedAccent[700]),
        child: new Stack([
          new Positioned(
              top: 100.0,
              left: 100.0,
              child: new Container(
                  child: new Stack([
                new Positioned(
                    top: 10.0, left: 10.0, child: new Text("Some text"))
              ]))),
        ]));
  }
}
```
**2.** Run this in debug mode to see that it renders correctly (```Some text``` appears on the screen)
**3.** Run the same ```App``` in checked mode.

**Expected result:**
**1.** The app is rendered correctly, the same way as in debug mode.

**Actual result:**
**1.** It crashes. The app fails on an assert. See the stack:
```Dart
The following RenderObject was being processed when the exception was fired (limited to 10 lines):
RenderStack relayoutSubtreeRoot=up1
  parentData: position=Point(100.0, 100.0); top=100.0; right=null; bottom=null, left=100.0
  constraints: BoxConstraints(0.0<=w<Infinity, 0.0<=h<Infinity)
  size: Size(Infinity, Infinity)
  child 1: RenderParagraph NEEDS-LAYOUT
    parentData: position=Point(0.0, 0.0); top=10.0; right=null; bottom=null, left=20.0
    constraints: null
    size: Size(0.0, 0.0)
    text:
      PlainTextSpan: "Some text"
The RenderObject had the following exception context:
  Widget build stack:
    AppContainer(hashCode=508237754; mounted; never synced; dirty; stateful})
    ReproApp(hashCode=785621802; mounted; never synced; dirty; stateful})
    Container(hashCode=210732031; mounted; never synced; dirty})
    Container(hashCode=647686895; mounted; never synced; dirty})
-- EXCEPTION --
The following exception was raised during paint():
'(...)/packages/sky/src/rendering/object.dart': Failed assertion: line 944: '!_needsLayout' is not true.
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      RenderObject._paintWithContext ((...)/packages/sky/src/rendering/object.dart:944)
#2      PaintingContext.insertChild ((...)/packages/sky/src/rendering/object.dart:308)
#3      PaintingContext.paintChild ((...)/packages/sky/src/rendering/object.dart:127)
#4      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint ((...)/packages/sky/src/rendering/box.dart:644)
#5      RenderStack.paint ((...)/packages/sky/src/rendering/stack.dart:236)
#6      RenderObject._paintWithContext ((...)/packages/sky/src/rendering/object.dart:961)
#7      PaintingContext.insertChild ((...)/packages/sky/src/rendering/object.dart:308)
#8      PaintingContext.paintChild ((...)/packages/sky/src/rendering/object.dart:127)
#9      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint ((...)/packages/sky/src/rendering/box.dart:644)
#10     RenderStack.paint ((...)/packages/sky/src/rendering/stack.dart:233)
#11     RenderObject._paintWithContext ((...)/packages/sky/src/rendering/object.dart:961)
#12     PaintingContext.insertChild ((...)/packages/sky/src/rendering/object.dart:308)
#13     PaintingContext.paintChild ((...)/packages/sky/src/rendering/object.dart:127)
#14     RenderProxyBox.paint ((...)/packages/sky/src/rendering/proxy_box.dart:80)
#15     RenderDecoratedBox.paint ((...)/packages/sky/src/rendering/proxy_box.dart:616)
#16     RenderObject._paintWithContext ((...)/packages/sky/src/rendering/object.dart:961)
#17     PaintingContext.insertChild ((...)/packages/sky/src/rendering/object.dart:308)
#18     PaintingContext.paintChild ((...)/packages/sky/src/rendering/object.dart:127)
#19     RenderView.paint ((...)/packages/sky/src/rendering/view.dart:109)
#20     RenderObject._paintWithContext ((...)/packages/sky/src/rendering/object.dart:961)
#21     RenderObject._repaint ((...)/packages/sky/src/rendering/object.dart:939)
#22     RenderObject.flushPaint ((...)/packages/sky/src/rendering/object.dart:908)
#23     SkyBinding.beginFrame ((...)/packages/sky/src/rendering/sky_binding.dart:85)
#24     WidgetSkyBinding.beginFrame ((...)/packages/sky/src/widgets/framework.dart:1499)
#25     Scheduler.beginFrame ((...)/packages/sky/src/animation/scheduler.dart:53)
```

**Comment by turu** [comment]
Note that setting _some_ of **BoxConstraints** types stops the assert from failing, while it still fails with other types set, so the issue is not purely down to no constraints being set for the inner container. 

Especially considering that it runs and displays perfectly fine in debug mode, this _may_ be an issue with the assert itself.

**Comment by abarth** [comment]
I would expect this app to throw an exception, but I would have expected a different exception than the one you're seeing.  The problem is that the inner stack doesn't know what size to be:

1) Because the inner stack is a positioned child of a stack, it is given unlimited width and height.
2) Because the inner stack has no non-positioned children, it tries to expand to fix its container.

At this point, it tries to expand infinitely into the unlimited width and height and should trigger an assertion.

**Comment by turu** [comment]
Ok, then two questions remain:
1) If it is forbidden, than shouldn't the API prevent me from doing it (for example by throwing a meaningful exception)?
2) Why is this kind of a tree forbidden if it actually renders well without checked mode turned on?

**Comment by turu** [comment]
And slightly on a side note, what if the stack with no non-positioned children, didn't try to expand to fit its container, but instead tried to expand enough to fit all of its positioned children? Just a wild thought.

**Comment by abarth** [comment]
> 1) If it is forbidden, than shouldn't the API prevent me from doing it (for example by throwing a meaningful exception)?

Yes, at a minimum, we're surfacing the wrong exception.

> 2) Why is this kind of a tree forbidden if it actually renders well without checked mode turned on?

The philosophy behind the checked mode / non-checked mode split is that checked mode generates many more errors that non-checked mode (e.g., assertions and type errors).  Non-checked mode keeps trying to execute until it hits an situation where it cannot recover (e.g., trying to read from null).  In this case, you're in a fragile situation, which the assert is trying to warn you about, but that happens to not hit a fatal error yet.

> And slightly on a side note, what if the stack with no non-positioned children, didn't try to expand to fit its container, but instead tried to expand enough to fit all of its positioned children?

We could try something like that, but it's not usually what the author wants.  For example, if they specify a right of 10.0, what that behavior would do is actually place the child in the upper left corner.

**Comment by abarth** [comment]
IMHO, this is working the way we intended.  Maybe we could improve the documentation or error handling to make this case clearer?
