### ISSUE TITLE
Tracing requires root

### ISSUE THREAD

**Issue by abarth** [flutter/engine#126]
We shouldn't require developers using Sky to have root on their device in order to use tracing.

**Comment by abarth** [comment]
One way to do this is to write the trace file out to the SD card, but that requires android.permission.WRITE_EXTERNAL_STORAGE

**Comment by j9brown** [comment]
Are we using Android systrace for this?  IIRC we have partial tools support
on user builds already.

Don't assume there's an sdcard or that it's necessarily accessible from
apps or from the shell.  We've been locking this down over time.

It wouldn't be hard to add a service or content provider to the Sky shell
to allow the shell user to access trace data.

**Comment by abarth** [comment]
It's not systrace.  It's Chromium's tracing system.  Gathering the data isn't a problem.  The problem is that we end up with this moderately large JSON blob in memory and need to send it back to the host machine somehow.

**Comment by j9brown** [comment]
Android Systrace == Chromium trace (more of less).  It's based on the
kernel ftrace buffer.  :)

If you actually have the data in ram, perhaps try using a service.  You
could implement the dump() method to return the buffer when provided
certain arguments.  Then from the shell use the dumpsys command to get what
you need.

**Comment by abarth** [comment]
Sounds great.  Any chance you have a link to some docs?

**Comment by j9brown** [comment]
Actually for that matter you can just dump an activity.

http://developer.android.com/reference/android/app/Activity.html#dump(java.lang.String,
java.io.FileDescriptor, java.io.PrintWriter, java.lang.String[])

**Comment by abarth** [comment]
https://github.com/flutter/tools/pull/100
