### ISSUE TITLE
Considering top-level functions for reduced-noise initializations?

### ISSUE THREAD

**Issue by sethladd** [flutter/engine#129]
Hi,

Sky code has a lot of nested object constructors, when component/widget trees are constructors. There's a lot of `new` going on.

I'm wondering if we considered making top-level functions that return new objects, in order to reduce the "noise".

Instead of:

`return new Center(child: new Text('Hello, world!'));`

What about:

`return Center(child: Text('Hello, world!'));`

Any thoughts?

**Comment by Hixie** [comment]
For my part I'd say the gain isn't worth the added complexity. (Also, without true metaclasses, I'm not really sure how we'd do it anyway.)

**Comment by abarth** [comment]
Closing this for now.  If we want less noise, we should probably go further in designing a tree building syntax.
