### ISSUE TITLE
Support 9-patch images

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1309]

**Comment by abarth** [comment]
Can you say specifically what you'd like to achieve?  You'd like a widget that takes 9 images and stretches them to conform to its layout size such that the corners aren't stretched, the top and bottom and only stretched horizontally, and the left and right are only stretched vertically?  (The center would be stretched both horizontally and vertically, presumably.

**Comment by apwilson** [comment]
Sort of.  In my particular situation I want the middle of my image to be stretched horizontally but I want the sides to maintain their aspect ratio - if that makes sense.

I don't expect to give 9 images but rather have a single nine patch image given that stretches as indicated in the image file.

Sort of like this: http://developer.android.com/tools/help/draw9patch.html

I suppose the same thing can be accomplished via nine images...

**Comment by apwilson** [comment]
http://radleymarx.com/blog/simple-guide-to-9-patch/

**Comment by krisgiesing** [comment]
it's equivalent to border-image in HTML/CSS, but with the dimensions of the CSS rule instead baked into the image.  I prefer the HTML/CSS semantics personally, as (a) it doesn't require any special tooling (Android provides a 9-patch editor) and (b) you could conceivably use the same image with different parameters to achieve different effects.

**Comment by apwilson** [comment]
Yep that's fine with me.  Adam mentioned dual x and y offsets to specify regions to stretch - that'll work for me.
