### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by ComsGen** [flutter/engine#1312]
When i run flutter on atom it tells me no module named urlparse
![err](https://cloud.githubusercontent.com/assets/7724090/10061305/f135e660-6257-11e5-96cf-262b17881836.PNG)

**Comment by devoncarew** [comment]
Which platform are you running on (windows?), and what version of python?

**Comment by ComsGen** [comment]
windows and  i have 3.x version of python

**Comment by devoncarew** [comment]
The `sky_tool` script we're using to launch apps on mobile devices doesn't currently work on windows. You can track the general issue here: https://github.com/flutter/tools/issues/36.

The plan is to re-write the python script into dart; that would set us up to better support windows. Closing this in favor of https://github.com/flutter/tools/issues/36..
