### ISSUE TITLE
Test with syntax error at run time times out

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1325]
The following test times out without an error message:

```dart
void main() {
   foo bar;
}
```

cc @abarth

**Comment by abarth** [comment]
The problem is that `await runZoned(() => new Future.sync(main), zoneValues: {` isn't catching the exception somehow.

**Comment by jason-simmons** [comment]
I don't think it's getting that far.

The sky_tools test loader is generating a Dart script that imports the test and then running that script in a subprocess.  If the test source is unparseable, then the subprocess will fail during the import and won't reach the runZoned call.

I looked into using deferred imports to fix this.  But the subprocess seemed to hang when the generated scripts waits for the deferred library to load.

**Comment by abarth** [comment]
The reason I thought it go to that line was that I added a bunch of prints and the prints up to that line executed.  There might have been a flaw in my experimental setup though because I needed to put in a bunch of hacks to get the print output to reach the console.

**Comment by jason-simmons** [comment]
I did some more investigation, and it looks like the execution of the Dart script is reaching runZoned.

The code is executed from ExecuteMicrotask in builin_natives.cc, which eventually calls Dart_InvokeClosure.  Dart_InvokeClosure returns a compilation error handle, which is different from an unhandled exception.

I can't find a way for the Dart code to intercept the compilation error with a catch or finally handler.

After Dart_InvokeClosure fails, the sky_shell process never exits.

**Comment by abarth** [comment]
Maybe we should `exit(1)` if we get a compilation error.  That's what we do in some other situations when we get an unrecoverable error.

**Comment by abarth** [comment]
Fixed in #1542
