### ISSUE TITLE
Curves should guarantee that at t=0.0, value=0.0

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1358]
Once this is fixed, we can remove the additional `_maybeCallOnResized()` call added in #1357.

**Comment by Hixie** [comment]
Specifically, at least `ease` does not currently guarantee this.

If we want this contract, we should assert that it is followed. (Same for v=1.0 at t=1.0.)

**Comment by j9brown** [comment]
Do we want any other constraints on these curves such as being monotonic or
always bound to the range [0.0, 1.0]?

**Comment by Hixie** [comment]
I don't think so. Consider a transition that makes a dialog expand from the middle of the screen, overshoot, then scale back a bit.

**Comment by abarth** [comment]
We have a bunch of curves that aren't monotonic and some that don't stay in [0.0, 1.0].
