### ISSUE TITLE
Dart/Skia bindings needed for game demo performance

### ISSUE THREAD

**Issue by vlidholt** [flutter/engine#138]
Bindings needed for SkCanvas (in order of priority):
- drawAtlas methods
- getTotalMatrix
- setMatrix
- drawVertices

The drawAtlas call has an example usage here (minus the canvas argument): https://github.com/domokit/sky_engine/blob/master/sky/sdk/example/game/lib/particle_system.dart#L275

    canvas.drawAtlas(texture.image, transforms, rects, colors, TransferMode.modulate,
              new Paint()..setTransferMode(transferMode));

If another way to transfer the rects and colors is considerably faster, that should probably be the way to do it (or possibly provide two methods).

**Comment by eseidelGoogle** [comment]
OK, so the only one I haven't done yet is drawVertices.  @vlidholt can you point me to a place in the game where you'd like to use drawVertices? Ideally also refactor that part of the game like you did for drawAtlas so I can just drop in the c++ version once I wire it up?

**Comment by eseidelGoogle** [comment]
An example for drawVertices:
https://github.com/vlidholt/sky_engine/blob/drawVertices/sky/packages/sky/example/game/test_spritemesh.dart

**Comment by abarth** [comment]
I believe we have most (all?) of these now.  If we're still missing any, please file separate bugs.
