### ISSUE TITLE
Mimic needs to also hoist the state of the original mimicable subtree

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1380]
Otherwise, running animations, etc, will be lost when you start mimiccing.

cc @apwilson, @abarth

**Comment by abarth** [comment]
I was thinking that we might want to drag state around in general for widgets with a global key.  When we insert a widget with a global key, we know the old version is going away, so we can grab its subtree (including state).

**Comment by Hixie** [comment]
We need to do more than drag that widget's state along. We have to drag the entire Element subtree along.

**Comment by abarth** [comment]
This should work now.  Whenever you give a widget a global key, it will drag its state along with it through the tree.  (Assuming its parent has a single child.)
