### ISSUE TITLE
Unwanted FlatButton Animation

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1385]
The setup is pretty simple: Column with 3 FlatButton.
Upon pressing the 3rd FlatButton, it becomes a Column with 6 FlatButton.
However, the 3rd FlatButton still animates after the screen change.

I don't want the button to animate because conceptually, it is not the same button. I am aware that there is some widget reuse going on behind the scenes and that using unique keys will likely sidestep the issue. However, is there a better way to avoid the animation?

**Comment by abarth** [comment]
The easiest thing is to use different keys when you're creating things that are semantically different.  If that's not sufficient, we can investigate other approaches.

**Comment by afandria** [comment]
I thought I'd responded earlier, but using keys is fine for me.
