### ISSUE TITLE
clamped_simulation.dart is missing?

### ISSUE THREAD

**Issue by mdakin** [flutter/engine#1428]
I am trying to build flutter engine but getting this error with ninja build:
[1001/152805:FATAL:loader.cc(21)] Check failed: base::ReadFileToString(path, &source). <...>/flutter/src/examples/rendering/packages/sky/src/animation/clamped_simulation.dart

Maybe the clamped_simulation.dart file is missing? The most recent change using it is this:
https://github.com/flutter/engine/commit/41926f9952e224c0aff1baac60e773b5da904d79

**Comment by HansMuller** [comment]
Sorry about, my fault. I will add the file now.

**Comment by HansMuller** [comment]
https://github.com/flutter/engine/pull/1429

Should land in a few minutes.
