### ISSUE TITLE
GlobalKey required in Focus

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1435]
It looks like any element (e.g., Input) that gets "focus" will run into the assert here:
https://github.com/flutter/engine/blob/5ca37e1f0b3ffed3bd43612ca042dc53fff182e1/sky/packages/sky/lib/src/widgets/focus.dart#L181

In other words, such widgets _must_ set the key parameter to a GlobalKey instead of leaving it as null. I think needing a key for some widgets is fine, but I think the [Tutorial](http://flutter.io/tutorial/#keys) should also mention that some Widgets require a GlobalKey. Right now, the tutorial makes it seem like keys are optional or nice to have for sync purposes, but I no longer think that this is the case.

**Comment by abarth** [comment]
Done: https://github.com/flutter/flutter.github.io/commit/6886bae4b966f75f88f5dad6c4bc0823371bd7c1
