### ISSUE TITLE
Size Observers with a child with zero width/height do not have their callbacks called

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1450]
Repro app:

```dart
void main() {
  runApp(new Container(child:new Center(child:new SizeObserver(callback: (size){print("Size: $size");}, child:new Container(width:0.0, height:0.0)))));
}
```

Change width or height to 1.0 and the callback gets called.

**Comment by abarth** [comment]
The problem is that RenderBox initializes its size to zero: `Size _size = Size.zero;`.  The `SizeObserver` doesn't think the size has changed and therefore doesn't call the callback.

**Comment by abarth** [comment]
We can probably initialize the size to null and avoid this problem since no one should be reading the size before layout anyway.

**Comment by Hixie** [comment]
PR: https://github.com/flutter/engine/pull/1453
