### ISSUE TITLE
FR: In-Place Rotation Widget

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1452]
I want to rotate some of my images and widgets around their center. (For now, it's in increments of math.PI/2 radians, but other angles would be good too.)

I can do so successfully under certain conditions:

```
// Shift the image such that its center is at the top-left corner.
// Then rotate (about its old top-left corner)
// Then translate it back.
new Transform(
  child: new NetworkImage("card.png"),
  transform: new vector_math.Matrix4.identity()
                .translate(this.width / 2, this.height / 2)
                .rotateZ(this.rotation)
                .translate(-this.width / 2, -this.height / 2)
```

This ought to work, but it requires that the image's width and height be known beforehand. Note that if the item in question is stretched (such as if it is inside a differently sized Container), then this transform no longer looks correct.

For simplicity, can there be a Rotation widget that rotates around the Widget's center without needing to write this transform explicitly and without knowing the width and height of the Widget?

**Comment by abarth** [comment]
Note: http://domokit.github.io/docs/sky/widgets/Transform-class.html has an `offset` property that will do the translations for you.  Sounds like you want to be able to set the origin in percents instead of in pixels (e.g., an origin of 0.5, 0.5 to transform around the center of the widget).

**Comment by abarth** [comment]
You should be able to do this with the new `alignment` property of `Transform`:

```dart
new Transform(
  alignment: new FractionalOffset(0.5, 0.5),
  transform: new Matrix4.identity().rotateZ(this.rotation),
  child: new NetworkImage("card.png")
);
```

**Comment by afandria** [comment]
Great, thanks!
