### ISSUE TITLE
Handle Android URL intents

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1459]
We should be able to follow a link to a specific stock in the stocks app, going to the '/stock/ABC' route for instance.

Launching the app from the home screen icon should go to the '/' route, not reopen whatever the most recently opened route was. (Test: go to a stock from another app, like a browser, then hit home, then hit stocks, then hit back - you shouldn't end up at the browser.)

**Comment by abarth** [comment]
Closing as duplicate of #776
