### ISSUE TITLE
Where's the OpenGL?

### ISSUE THREAD

**Issue by unicomp21** [flutter/engine#1482]
Do we have ES 3.0?

**Comment by abarth** [comment]
Internally Flutter uses OpenGL to draw, but we don't currently expose OpenGL to authors.  Instead, we expose a 2D drawing API via the `Canvas` interface: http://domokit.github.io/docs/sky/rendering/PaintingCanvas-class.html

**Comment by unicomp21** [comment]
Are there plans to expose it?

**Comment by abarth** [comment]
It's something we want to implement in the long term, but we don't have any plans to expose it in the near term.
