### ISSUE TITLE
Considering moving examples to own repo?

### ISSUE THREAD

**Issue by sethladd** [flutter/engine#1491]
Now that we have our own org, would it make sense to move examples out of engine and into their own org?

Or are things moving too fast right now...

**Comment by j9brown** [comment]
Someday for sure, but I suggest we wait until we figure out the layout
we'll want for our Jiri repos.

**Comment by abarth** [comment]
We very often change the examples atomically with the framework.  Once the framework settles down, I imagine we'll do that less.

I'd like to separate the Dart code from the C++ code though.  That way the Dart part can be more approachable.
