### ISSUE TITLE
Traceback for skytools and python subprocces.py(Atom Editor)

### ISSUE THREAD

**Issue by ComsGen** [flutter/engine#1505]
```
Traceback (most recent call last):
  File "packages/sky/sky_tool", line 1320, in <module>
    sys.exit(SkyShellRunner().main())
  File "packages/sky/sky_tool", line 1311, in main
    exit_code = args.func(args, pids)
  File "packages/sky/sky_tool", line 266, in run
    started_sky_on_android = android.setup_servers(sky_server_root, main_dart, pids, args)
  File "packages/sky/sky_tool", line 496, in setup_servers
    sky_server_pid = _start_http_server(sky_server_port, sky_server_root)
  File "packages/sky/sky_tool", line 80, in _start_http_server
    return subprocess.Popen(server_command, cwd=root).pid
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

i dont understand the error

**Comment by iansf** [comment]
Can you share the sky_tool command line invocation that you are using when that error happens?

**Comment by abarth** [comment]
Interesting.  It looks like it's having trouble starting the local HTTP server...

**Comment by ComsGen** [comment]
I'm using atom i forgot to mention that so i just click on run application

**Comment by iansf** [comment]
@devoncarew, any thoughts?

**Comment by devoncarew** [comment]
No ideas, but some things you can try. From the command line (in directory w/ the app), can you run:

```
pub update
```

to make sure you have the latest `sky_tool`, and then

```
./packages/sky/sky_tool stop
```

to try and stop any previous processes running. You can then try re-running from atom, or try `./packages/sky/sky_tool start` from the CLI, to see if you get more info that way.

**Comment by ComsGen** [comment]
okay

**Comment by Hixie** [comment]
Has the Atom dart plugin been updated to use the 'flutter' tool from 'pub global activate flutter'? If so, does that still cause the problem?

**Comment by devoncarew** [comment]
It's hasn't - it's still on the `sky_tool` script. ETA is most likely the next release (~Tuesday).

**Comment by devoncarew** [comment]
https://github.com/dart-atom/dartlang/issues/423

**Comment by abarth** [comment]
https://github.com/dart-atom/dartlang/issues/423 looks to be fixed, hence I believe this issue is fixed.
