### ISSUE TITLE
Cannot find sky_viewer.mojo

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1510]
Approximately, I'm doing this:

```
pub run sky_tools -v --very-verbose run_mojo \
	--mojo-path $MOJO_DIR/src \
	--app app.flx --android \
	-- \
	--enable-multiprocess \
	--args-for="mojo:sky_viewer --enable-checked-mode"
```

Unfortunately, `sky_viewer.mojo` seems to have disappeared. (I could find it yesterday.)

```
Error (-105: net::ERR_NAME_NOT_RESOLVED) while fetching https://storage.googleapis.com/mojo/sky/viewer/android-arm/87960ec1c2e380b9190d0b8a2c333ae5d09c940d/sky_viewer.mojo
```

**Comment by afandria** [comment]
The one for Desktop seems to be there.

**Comment by afandria** [comment]
Never mind, I can confirm that both are present. It works for phones actually connected to the internet, which means that the devices are the ones downloading sky_viewer.mojo. It looks like the phone I was using decided to disconnect.

**Comment by jamesr** [comment]
If you'd like we could teach the host to download the viewer for Android itself. Using the device to fetch the viewer had nice caching properties but this failure mode is surprising.

**Comment by afandria** [comment]
That would have helped, but something like that wouldn't be a high priority for me. I don't want my Android devices to be overly reliant on the host, since they'll have to run alone in .apk form.

One possible reason that a cached version wasn't available for the device is that a new flutter/sky package was recently pushed, so the device may not have had that the new `sky_viewer.mojo`.
