### ISSUE TITLE
FlatButton Behavior when pressing Edges

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1525]
I've been tapping the edges of a FlatButton. It animates but does not fire onPressed. It works normally when I press a more central area of the button.

I have placed the button within a Flexible and Row.
Text < Container with border and padding < FlatButton < Flexible < Row

**Comment by abarth** [comment]
This behavior is a result of moving the gesture detection into the InkWell.

IMHO, the sensible thing to do here is to not animation when pressing on the edges and instead animate only when onPressed would be triggered.

**Comment by afandria** [comment]
Thanks!
