### ISSUE TITLE
Drawers are no longer stateful

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1528]
e.g. the card_collection.dart demo's drawer's checkboxes don't check when you tap them.

**Comment by abarth** [comment]
Interesting.  It's not clear to me how to fix this bug.  The stock menu tries to solve this problem by calling setState on the navigator, which seems a bit wonky.

**Comment by abarth** [comment]
I guess we can make the contents of the drawer a stateful component and then call setState on that.

**Comment by abarth** [comment]
This issue applies to menus now too.
