### ISSUE TITLE
Paint functions use save/restore around children

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1537]
For example, RenderStack.paint() uses `context.canvas.save();` and `context.canvas.clipRect(offset & size);`. This in theory will fail once things use layers.

There are several problems here:
- [ ] RenderStack.paint() uses save/restore around paintChild.
- [ ] The assert that's supposed to catch this isn't firing.

(Add any other paint() functions that do this to the list above as you find them.)

cc @abarth, @chinmaygarde

**Comment by abarth** [comment]
There are a bunch of these.  Grep for `context.canvas.save`
