### ISSUE TITLE
Pointer events don't give screenX and screenY

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#156]
_From @abarth on January 16, 2015 7:58_

We have this in ui::Event and in web input events.  Seems like we should have it for pointer events too.

_Copied from original issue: domokit/mojo#36_

**Comment by Hixie** [comment]
How would you use this?

**Comment by Hixie** [comment]
_From @abarth on February 12, 2015 4:37_

To coordinate with other apps on the screen that are in some other coordinate system from you.

**Comment by Hixie** [comment]
Ah, yeah, that makes sense.

**Comment by Hixie** [comment]
@abarth might want to take this for his pointer work

**Comment by abarth** [comment]
This is obsolete now.
