### ISSUE TITLE
Tutorial docs are out of date

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/engine#1599]
In the [tutorial](http://flutter.io/tutorial/), the sample code for routes needs updating. It currently shows:
```
 routes: {
      '/', (NavigatorState navigator, Route route) => new DemoHome();
    }
```

It should show:
```
 routes: {
      '/': (RouteArguments args) => new DemoHome()
    }
```
The changes are:
1. The comma changes to a colon.
2. The arguments to the function change.
3. Trailing semicolon goes away.

**Comment by abarth** [comment]
https://github.com/flutter/flutter.github.io/pull/28

We now run tests on this code.  That code snippet was whitelisted as known buggy.  Hopefully that PR will fix it.

**Comment by abarth** [comment]
Ok. It's slightly harder than that.  /me will fix.

**Comment by abarth** [comment]
Looks like the only skipped code snippet is now for something that's not intended to be actual runnable code.
