### ISSUE TITLE
NetworkInterface.list() crashes

### ISSUE THREAD

**Issue by kyorohiro** [flutter/engine#1655]
Following code cause to crash application 

[source]
import 'dart:io';
import 'dart:convert';
import 'dart:async';

main() async {
  List<NetworkInterface> interfaces = await NetworkInterface.list(
      includeLoopback: true, includeLinkLocal: true);
}

[project]
https://github.com/kyorohiro/hello_skyengine/tree/master/dartio_networkinterface

**Comment by jason-simmons** [comment]
This API is not implemented in Dart for Android.  See Socket::ListInterfaces in dart/runtime/bin/socket_android.cc.

Socket::ListInterfaces is also not setting the OSError.  CObject::NewOSError then consumes the null OSError, resulting in a segfault.
