### ISSUE TITLE
show software keyboard and push delete key, then crash application

### ISSUE THREAD

**Issue by kyorohiro** [flutter/engine#1662]
show software keyboard and push delete key, then crash application

**[source]**
```
import 'package:flutter/widgets.dart';
import 'package:flutter/services.dart';

main() async {
  EditableString st= new EditableString(text: "test:", onUpdated: () {});
  keyboard.show(st.stub, KeyboardType.TEXT);
}
```

**[senario]**
1. run applicatioon on nexus7
  https://github.com/kyorohiro/hello_skyengine/tree/master/edit_text_2
--> show software keyboard
2. push delete key

**Comment by jason-simmons** [comment]
The Android keyboard/IME state needs to be kept in sync with the editable text.  For example:
    EditableString st = new EditableString(text: "test:", onUpdated: () {}, onSubmitted: () {});
    KeyboardHandle handle = keyboard.show(st.stub, KeyboardType.TEXT);
    handle.setText(st.text);
    handle.setSelection(st.text.length, st.text.length);

EditableString isn't really suitable for standalone use.  Instead, use an Input widget, which contains this logic.
