### ISSUE TITLE
NetworkImage occasionally does not load (continued)

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1664]
Using flutter 0.0.4. The solution in #801 may not have been applicable to my app, after all. There aren't any Sky errors printed out to stdout (or adb logcat).

I am building the .flx file with all my image assets pointed to in the manifest.yaml. I start Sky with `pub run sky_tools -v --very-verbose run_mojo` (and other options including --enable-multiprocess).

Related #1072

**Comment by abarth** [comment]
Darn.  We'll keep working on it.
