### ISSUE TITLE
fetchUrl does not call close() on exceptions

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/engine#1680]
In sky/packages/sky/lib/src/services/fetch.dart, loader.close() is not called if an exception is thrown. I would propose that loader.close() should be called in a try/finally block.

**Comment by abarth** [comment]
Yes, definitely.  Are you interested in sending a pull request to fix this issue or would you prefer that I fix it?

**Comment by jimbeveridge** [comment]
I will send a pull request.

**Comment by abarth** [comment]
Thanks!
