### ISSUE TITLE
dart:ui should have a method to push the data to the GPU

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1682]
...so that we can call it during the frame as soon as we have the data ready, before we deal with cleanup, scheduling the next frame's animations, etc.

If we do that, we can move the call to GlobalKey._notifyListeners() in Element.finalizeTree() to just be an inline call rather than a call through scheduleMicrotask().

**Comment by abarth** [comment]
`ui.window.render` now lets you signal that you want to push to the GPU but it's not wired up to do that in C++ yet.
