### ISSUE TITLE
Container Sizing help

### ISSUE THREAD

**Issue by afandria** [flutter/engine#1689]
I wanted to create a Container of fixed size at the top level of my app, but no matter what I did (regardless of width, height, constraints, and parents chosen), I couldn't get it to actually respect the sizes I placed on it (200.0 width, 50.0 height).

Instead, the Container would always expand as much as it could (in other words, taking up the whole screen).

I ran into this while trying to report a bug on Containers and BuilderTransition. The BuilderTransition works with CustomPaint, Text, and BoxDecoration (backgroundColor), but I couldn't get it to work with Container (width).

I wanted to simulate the LinearProgress bar by having a large container of fixed size hold a smaller container of variable size. However, it looks like the problem may be that regardless of BoxConstraints and explicit width and height settings, these Containers always try to grow to fill their parent.

Example (_paint is a slightly modified copy of LinearProgressIndicator's _paint function):

```
    new BuilderTransition(
      variables: <AnimatedValue<double>>[_performance.variable],
      performance: _performance.view,
      builder: (BuildContext context) {
        int x = 100 + 100 * (9 * _performance.value).floor();
        return new Container(
          width: 200.0,
          height: 50.0,
          child: new Container(
            width: 200.0 * _performance.value, // The width does NOT change; it's always maximal. I also tried constraints.tight/tightFor/loose/expand but none of them helped.
            decoration: new BoxDecoration(backgroundColor: Colors.blue[x]), // background color changes
            child: new Text("${_performance.value}") // text changes
          ),
          /*child: new CustomPaint( // This animates when uncommented (and the other child is commented)
            token: _performance.value,
            callback: (Canvas canvas, Size size) {
              _paint(context, _performance.value, canvas, size);
            }
          ),*/
          decoration: new BoxDecoration(backgroundColor: Colors.grey[500])
        );
      }
    )
```

**Comment by abarth** [comment]
Yes, the root widget is given tight constraints to make it fill the screen.  Generally, you want to pick some sort of layout model relatively high in your widget tree.  Many of the simple examples use `Center` to center a single widget on the screen.  You can also use `Row` or `Column` depending on what you'd like.  In the web, the default layout model is `Block`, which you can also choose if that's what you want.

**Comment by afandria** [comment]
Thanks, that makes sense. It looks like these layout widgets (Center/Row/Column/Flex/Stack/Block?) are very important for walling off and enforcing constraints.

Let's say I am within a Column, and one of my children is that Container (it shows up as 200 by 50). How can I modify the parent-child relationships so that my inner Container's width can animate (between 0 and 200)?

**Comment by afandria** [comment]
I inserted Flex, and it worked!

**Comment by abarth** [comment]
> Let's say I am within a Column, and one of my children is that Container (it shows up as 200 by 50). How can I modify the parent-child relationships so that my inner Container's width can animate (between 0 and 200)?

By default, `Column` lets the child be a narrow or as wide as it liked.  That means you can just animated the width property of the `Container`.

```dart
  return new Column([
    new Container(width: _widthAnimation.value)
  ]);
```

**Comment by afandria** [comment]
Thank you!
