### ISSUE TITLE
Can't tap on row at the bottom of the stocks list

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1707]
Pretty sure this isn't the first time we've had this bug. We should make sure to add a test when we fix it.

**Comment by Hixie** [comment]
@abarth I suspect this is because the scaffold is actually positioning the fab across the whole bottom of the screen instead of just where the fab needs to be.

**Comment by abarth** [comment]
That makes sense.  The fab and the snackbar are in a render object together.  This gets back to the question how how to hit test non-visual render objects.

**Comment by Hixie** [comment]
Yeah, if we're sticking with the Stack-based Scaffold then we should probably solve this using the solution for #53.

The old non-Stack based scaffold didn't have this problem because it manually positioned the fab above the snack bar. That's one advantage of dedicated render boxes.

**Comment by abarth** [comment]
@HansMuller fixed this issue.
