### ISSUE TITLE
Event funneling

### ISSUE THREAD

**Issue by HansMuller** [flutter/engine#1726]
If I add a single event handling child to a larger container that just adds some decoration, sometimes I'd like to be able to say that events that occur within the container should be delivered to the event handling child. As if they'd actually targeted the child.

For example: put a button inside a container that adds some padding and a border. It would be nice if it were possible to funnel gestures that landed outside the button but within the container, to the button. So that the entire thing acted like the button.

**Comment by krisgiesing** [comment]
I think this would only matter if the child is stateful. If it's stateless, the parent can just wrap the whole container in a GestureRecognizer and ignore the callback parameter to the child. (It does somewhat undermine the utility of the callback, though.)
