### ISSUE TITLE
Tap gesture doesn't eat secondary taps

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1779]
If you have a button, and you interact with it in the following sequence:
1. Finger 1 down
2. Finger 2 down
3. Finger 2 up
4. Finger 1 up
...it triggers when the second finger comes up. It should only trigger when the first finger comes up, secondary touches should just be eaten and ignored.

**Comment by krisgiesing** [comment]
I don't think that's right. What if you want to support something like Plants Vs. Zombies, where you can tap in multiple places in the canvas at once? As long as all taps obey their slop, I think we should trigger as many as actually occurred.

**Comment by Hixie** [comment]
I agree we should supports a PvZ-style tap gesture recogniser. I think that should be separate from the gesture recogniser we have for material buttons, though.

**Comment by krisgiesing** [comment]
As per discussion, will move current tap implementation to a different recognizer, and restore previous tap behavior.
