### ISSUE TITLE
CanvasImage leaking memory when called from dart

### ISSUE THREAD

**Issue by alhaad** [flutter/engine#1788]
CanvasImage's destructor (https://github.com/flutter/engine/blob/master/sky/engine/core/painting/CanvasImage.h) is not being called from dart when an image is repeatedly created using decodeImageFromDataPipe causing an eventual out-of-memory.

The crash takes place when about 140 CanvasImage objects are created.

**Comment by abarth** [comment]
Do they eventually get collected if you run the app long enough?  Meaning, is the problem that we aren't running GC soon enough or that the process for freeing these objects in GC is busted?

**Comment by alhaad** [comment]
No GC starts (i.e the destructor is not called) by the time we crash. I'll check and see if waiting *longer* helps.

**Comment by abarth** [comment]
I wouldn't assume that GC starting and the destructing being called are the same thing.  It's quite possible that GC runs and we fail to delete the object for some reason.

**Comment by jamesr** [comment]
Does the Dart VM provide equivalents of V8's --trace-gc set of flags? @johnmccutchan 

That aside, this is not the sort of object that we want to rely on garbage collection for.  The Dart interface needs to provide an explicit way to release the backing memory and the application code / framework need to call these to release the images at the appropriate time.  GC can be a fallback.

**Comment by abarth** [comment]
Yeah, I just wanted to make sure we understood the problem before fixing it.

**Comment by johnmccutchan** [comment]
The Dart VM has --verbose_gc which will print to standard output whenever a GC occurs. You can also get the same information from VM's timeline.

**Comment by chinmaygarde** [comment]
I have definitely observed GC information on the VM's timeline. You can enable the tracing via the `TracingController` attached to the shell. AFAIK, there are no Dart bindings for this. I can add the same if necessary.

**Comment by johnmccutchan** [comment]
@chinmaygarde https://api.dartlang.org/134482/dart-developer/Timeline-class.html

**Comment by jason-simmons** [comment]
Fixed (https://github.com/flutter/engine/pull/1837)

**Comment by alhaad** [comment]
We are seeing the memory leak again. It seems to me that the fix made in #1837 got reverted in #1861.
@jason-simmons Could you please take a look?

/cc @gauthamt
