### ISSUE TITLE
method not found: 'pointer' on mouseover event

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/engine#1806]
MouseOver events generate the following stackdump running the `examples/widgets/scale.dart` sample code under Mojo shell under Linux:

```
[1026/150556:ERROR:dart_error.cc(16)] Unhandled exception:
The null object does not have a getter 'pointer'.

NoSuchMethodError: method not found: 'pointer'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      _UiEventConverter.convertPointerEvent (packages/flutter/src/rendering/binding.dart:98)
#3      _UiEventConverter.convert (packages/flutter/src/rendering/binding.dart:47)
#4      FlutterBinding._handleEvent (packages/flutter/src/rendering/binding.dart:181)
```

To repro, run examples/widgets/scale.dart like this and move the mouse around the window:
`pub run sky_tools build --main=scale.dart && pub run sky_tools run_mojo --mojo-path ~/mojo/src`

(requires a Mojo build to be present in ~/mojo/src.)

This problem happens on all of the samples I've tried.

**Comment by krisgiesing** [comment]
Looking
