### ISSUE TITLE
Unable to get touch locations in Tap, Pan or Scale events.

### ISSUE THREAD

**Issue by debreuil** [flutter/engine#1807]
Use cases:
Tap on a map to place a pin.
Drag finger across the screen and leave a trail.
Show touch indicators on scale or pinch gestures (requires each finger's location).

The GestureScaleUpdateCallback has the focalPoint which is similar, but it would be nice to have access to each finger location in multi-finger versions of all of these.

**Comment by abarth** [comment]
In the next release, you'll be able to get the global coordinates of the tap in `onTapDown` and `onTapUp`.  I'll add the coordinates to dragging shortly.

**Comment by abarth** [comment]
The drag starts no give you the global coordinate at which the drag starts as well.

**Comment by abarth** [comment]
s/no/now/
