### ISSUE TITLE
material.Icon should use an enum rather than an int for size

### ISSUE THREAD

**Issue by ianloic** [flutter/engine#1816]
Material design icons are defined to work at specific sizes: 18, 24, 36, 48. The current API doesn't reflect that and just takes a size int. If an invalid size is chosen an error is printed to the console and no icon shows up.

**Comment by abarth** [comment]
Yeah, we should probably also have constants for all the different icon types too given that there is a finite list of them.  That might also help with automatically determining which assets to include in the FLX.
