### ISSUE TITLE
Only 24dp material design icons are included

### ISSUE THREAD

**Issue by ianloic** [flutter/engine#1817]
When I try to reference a material.Icon with a size of 18, 36 or 48 I get an error like:

    Requested asset 'toggle/drawable-xxhdpi/ic_star_black_18dp.png' does not exist.

even though those are legitimate material icon sizes.

**Comment by abarth** [comment]
I think you can just add these sizes to this line of code:

https://github.com/flutter/tools/blob/master/lib/src/commands/build.dart#L20

We need a better system for determining which assets to include in your FLX.  At a minimum, we could make this configurable in the `flutter.yaml` file.  In the best case, we'd have a way to automatically detect which assets you needed by statically analyzing your code (e.g., by having a constant for each asset and applying tree shaking).

**Comment by IvBaranov** [comment]
I am not sure I should start new issue so:
Demo project _my_app_ prints: 
`[WARNING:asset_bundle_impl.cc(45)] Requested asset 'content/drawable-xxhdpi/ic_add_white_24dp.png' does not exist.`

**Comment by ianloic** [comment]
I just worked out that I can specify a size for icons that I list in my flutter.yaml file. I have to do it for each icon and can't specify a list of sizes but it works.

**Comment by IvBaranov** [comment]
There should be some sort of a section about `flutter.yaml` file.
