### ISSUE TITLE
Expose Material shadows to 3rd party widgets.

### ISSUE THREAD

**Issue by ianloic** [flutter/engine#1821]
When writing a custom widget in Flutter that will be in a Material app, to get the same shadows as are used in the stock material widgets I need to do ugly stuff like:

    import 'package:flutter/src/material/shadows.dart' as material_shadows;

It should be possible to access those definitions in a more direct, stable manner.

**Comment by abarth** [comment]
Why not just import `import 'package:flutter/material.dart'` ?  Then you can access shadows for height 3 as `shadows[3]`

**Comment by Hixie** [comment]
Yeah, you should never need to import anything with `/src/` in the path.

**Comment by ianloic** [comment]
Oops. I failed to notice the weakness of dart namespacing :(
