### ISSUE TITLE
Widget constructors expect children in inconsistent ways

### ISSUE THREAD

**Issue by ianloic** [flutter/engine#1872]
Some widgets (eg: Container) require a name `child:` argument to specify their children. Others (eg: Flex) take their children as the first argument. This inconsistency is confusing - especially as I switch between different container widgets.

**Comment by abarth** [comment]
Yeah, the pattern we've been using is that if you take one widget as a child, you use the name `child`.  If you take a list, then you use a positional argument.  Are you suggesting that we make the list widgets use the name `child` too?  Maybe `children`?

**Comment by ianloic** [comment]
I don't have a concrete suggestion other than it's a little confusing. Perhaps make the list widgets use children so that I'm forced to be explicit everywhere.
