### ISSUE TITLE
Request to document Material

### ISSUE THREAD

**Issue by sethladd** [flutter/engine#1874]
Was looking at sample code in the Tutorial, and it used a Material class. I wanted to know what that was for, but didn't see docs for it in my editor (Atom)

![screen shot 2015-10-29 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/5479/10831923/97f3ceb4-7e45-11e5-9c46-e88aecb155e9.png)

**Comment by abarth** [comment]
Yes, we need to add more dartdoc to the higher levels of the system.
