### ISSUE TITLE
big_red_button.py should run the same tests as travis

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1880]
Somehow we should verify that the release we're about to make will be analyzer-clean and pass the tests. This is complicated by the fact that during the release your tree is in a state where 'pub' won't be happy, of course.

**Comment by abarth** [comment]
I discussed this with @sethladd .  One idea is to be able to push a "beta" or "dev" version of the packages to pub that won't be visible to the public.  Then we could test them from pub and once they pass the test, we could flip the bit on the server and make them the production versions of the package.
