### ISSUE TITLE
Feature Request: setStrokeCap: Expose ability to paint a path (Canvas.drawPath) with different stroke caps

### ISSUE THREAD

**Issue by jestelle** [flutter/engine#1887]
I want to be able to draw a stroke on a canvas, and use different line end caps:
butt OR round OR square

Appears to me that Skia can handle this:
https://fiddle.skia.org/c/828b79b9011bfdd6c805a819a5675839

**Comment by abarth** [comment]
Yep, looks like an easy addition to the Canvas API.
