### ISSUE TITLE
Inform developer when a character is used that has no glyph in the available fonts

### ISSUE THREAD

**Issue by cpu-chromium** [flutter/engine#189]
https://github.com/domokit/sky_engine/blob/master/sky/sdk/example/mine_digger/lib/main.dart

On Linux it shows the correct character, a flag; not so in android 
new StyledText(elements : [Game.textStyles[5], '\u2691'])

However, u2600 works in android
new StyledText(elements : [Game.textStyles[3], '\u2600'])

This can be as simple as the default font not having that codepoint. In this case it would be good to have that pointed at develop time.

Note the text styles defined as:
textStyles.add(new TextStyle(color: const Color(0xFF555555), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF0094FF), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF13A023), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFFDA1414), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF1E2347), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFF7F0037), fontWeight: bold));
textStyles.add(new TextStyle(color: const Color(0xFFE93BE9), fontWeight: bold));

**Comment by cpu-chromium** [comment]
Chrome has the same behavior, showing 2600 but not 2691. Apparently stock android only has Roboto and Noto fonts. But an android app can embed ttf fonts, so this bug could mutate into providing font support outside these two fonts.

**Comment by Hixie** [comment]
See #228 for general embedded font support.
