### ISSUE TITLE
APIs that take List<X> should take Iterable<X>

### ISSUE THREAD

**Issue by ianloic** [flutter/engine#1903]
I'm often finding myself using List.map to turn a list of data objects into a list of widgets as children or menu items. Every time so far I've forgotten to .toList(). Is there a reason that the APIs that need a list of things don't just take an Iterable?

**Comment by abarth** [comment]
/cc @Hixie 

We tried using Iterable at one point, but I don't remember when we ended up going back to List.  Ian do you remember?

**Comment by Hixie** [comment]
I forget the details, but it was in fn2, so it might no longer matter. We can try again.

**Comment by sethladd** [comment]
Bonus: using Iterable means you can use `yield` :)
