### ISSUE TITLE
Travis should try to create a new app and analyze it

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1919]
That way we would catch cases where we've changed the API but the template app was not updated.

**Comment by devoncarew** [comment]
We're doing that here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/init_test.dart. It creates a new app using `flutter init`, runs pub, and analyzes the result. Is that what you had in mind?

**Comment by sethladd** [comment]
That's a good start, but I've run into at least one case where the code analyzes cleanly but the app was broken. For example, some of our widgets require themselves to be nested inside a MaterialApp. Not sure how we'd test for that, but curious if there's a way.

**Comment by Hixie** [comment]
@devoncarew  That's what I had in mind. We previously weren't doing that when you would update the framework, so it would break and nobody would notice. That should be fixed with the new setup.

@sethladd Yeah, dunno how we'd test that.
