### ISSUE TITLE
Checkbox + label should be a widget

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1925]
Any time you add a checkbox, you end up having to add a label also, and then hooking up the event handlers on both, and it's a pain. We should just have one widget that has a checkbox and a label.

Same for radio buttons, switches, etc.

**Comment by HansMuller** [comment]
Making it easy to funnel events from widgets (like labels) added to an event handling widget (like Checkbox) might be worth supporting.  See  https://github.com/flutter/engine/issues/1726
