### ISSUE TITLE
Canvas doesn't have an "addTransform()" operation

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#1957]

**Comment by abarth** [comment]
http://domokit.github.io/docs/sky/painting/Canvas/concat.html

**Comment by krisgiesing** [comment]
Method should maybe be called concatMatrix?  As it stands it seems like it's concatenating a canvas with a matrix, rather than two matrices.

**Comment by Hixie** [comment]
oh hey, there it is. oops.
