### ISSUE TITLE
flutter start incorrectly says no connected devices when more than one connected.

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#1963]
$ adb devices
List of devices attached 
061c775e00fa9f48	device
d6ba8ac	device

$ flutter start --checked
Unable to run application - no connected devices.

**Comment by jason-simmons** [comment]
Currently the flutter tool does not have an option for selecting an Android device ID.

You can work around this by setting the ANDROID_SERIAL environment variable:
    ANDROID_SERIAL=061c775e00fa9f48 flutter start --checked

**Comment by abarth** [comment]
I think @jason-simmons fixed this issue.

**Comment by jason-simmons** [comment]
Fix landed: https://github.com/flutter/flutter/pull/34
