### ISSUE TITLE
Android back button does not do navigator.pop() when using run_mojo

### ISSUE THREAD

**Issue by aghassemi** [flutter/engine#1973]
I am running my MaterialApp in Mojo so it is using Mojo Shell instead of Sky Shell. This difference seems to be causing back button to exit the app rather than poping from navigator.

@abarth @Hixie

**Comment by abarth** [comment]
There's no back button integration in MojoShell on Android.

**Comment by abarth** [comment]
@jamesr @j9brown Who's the right person to handle feature requests for MojoShell on Android?

**Comment by jamesr** [comment]
@qsr is

**Comment by tonygentilcore** [comment]
I believe the mojo issue tracking this is https://github.com/domokit/mojo/issues/361
