### ISSUE TITLE
OnePlus One on Marshmallow doesn't display FloatingActionbar icons

### ISSUE THREAD

**Issue by JapSeyz** [flutter/engine#1987]
Just running the stock download-able template from the **flutter init** command shows no icon in the FloatingActionbar, even though it is defined in the code as **icon: 'content/add'**

I am using an OnePlus One running Marshmallow through OmniRom.
Running Flutter from a Mac from El Capitan.

![screenshot_20151106-135708](https://cloud.githubusercontent.com/assets/2234034/10997701/7c1a86d8-848f-11e5-9f60-b325af08e4d7.png)

**Comment by abarth** [comment]
I suspect you're running into #1664.  We're need to dig into the issue more to understand what's causing it.

**Comment by devoncarew** [comment]
I see this as well. This repros when run via `--no-http`, but not when run with `--http`.

**Comment by JapSeyz** [comment]
It could be. I tried to run it a couple of times, nothing seemed to change.

**Comment by devoncarew** [comment]
I think the same resolution as here: https://github.com/flutter/tools/issues/177 - you'll need to create a flutter.yaml file and list the `content/add` icon in it.

**Comment by JapSeyz** [comment]
Alright. 
This is supposed to be done automatically right? Otherwise it's kinda counter intuitive to have to declare everything twice

**Comment by abarth** [comment]
Automatic detection is https://github.com/flutter/engine/issues/1914

**Comment by JapSeyz** [comment]
Perfect
