### ISSUE TITLE
Publish some example apps in the Play Store and in the App Store

### ISSUE THREAD

**Issue by trusktr** [flutter/engine#2000]
Got any links?

**Comment by abarth** [comment]
We don't have any examples published in Android Play or in the App Store yet.  That's something we'll certainly do.  It's just a question of when.

**Comment by mscheel** [comment]
At the bottom of this page (http://flutter.io/getting-started/) it says the Stocks.apk is available here: https://github.com/flutter/engine/tree/master/examples/stocks but the APK folder does not have an APK.  Either the web page needs to be corrected or the APK should be added.

**Comment by abarth** [comment]
If you follow the instructions for contributing to engine.git and run the build, you'll produce a Stocks.apk.  We should make the docs clearer in that regard.

**Comment by sethladd** [comment]
cc @vlidholt
