### ISSUE TITLE
Error starting app while both emulator is running and real device is connected

### ISSUE THREAD

**Issue by nalkon** [flutter/engine#2011]
If you try to install flutter app (flutter start) while both Android emulator is running and real device is connected, you get an error:

Unable to run on Android.
Unable to run application - no connected devices.

OS: Ubuntu 14.04

**Comment by abarth** [comment]
I suspect @jason-simmons fixed this recently.  (At least he fixed a similar issue with multiple physical devices.)  We need to publish a new release with the fix.
