### ISSUE TITLE
Opening file '/data/data/org.domokit.sky.shell/dev.flx' failed

### ISSUE THREAD

**Issue by josephburnett** [flutter/engine#2014]
When running `flutter start` I see this in the logs.  The app starts but it is just a black screen.

android: E/chromium: [ERROR:data_pipe_file_utils.cc(233)] Opening file '/data/data/org.domokit.sky.shell/dev.flx' failed in CopyFromFileHandler::OpenFile

Ubuntu 14.04 running in VMWare connected to a Samsung Galaxy SIII with Flutter 0.0.18

**Comment by abarth** [comment]
We've published a new version that should hopefully fix this issue.  The new version has different setup instructions, so you might need to run `pub global deactivate flutter` and follow the new instructions to get this working.

**Comment by abarth** [comment]
http://flutter.io/getting-started/ has the new instructions.
