### ISSUE TITLE
The amount of boilerplate needed to add a dialog to hello world is excessive

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#243]
- [x] ~~You have to create a Navigator.~~
- [x] ~~You have to create a NavigationState to pass to the Navigator.~~
- [x] ~~You have to have an initState() method to create that object, so that it can have a default route.~~
- [x] **You have to shuttle the Navigator around to your build function and its subfunctions for that default route.**
- [x] ~~You have to have a stack to hold the dialog on top of your default content.~~
- [x] ~~You have to both push a state on that navigator AND set some internal state just to know to show the dialog.~~
- [x] ~~You have to have an explicit callback to change that internal state back to not show the dialog.~~
- [x] **You have to have a builder for the dialog** ~~which you can call from the build function that has the navigator and the Stack.~~
- [x] ~~You have to handle how to hide the dialog (navigator.pop) in three places in the dialog's own builder.~~
- [x] ~~You have to manage focus for the dialog, especially if it has a text field.~~

cc @abarth @collinjackson

**Comment by Hixie** [comment]
I made some progress on this earlier today. Most of the remaining issue is around the boilerplate for having a Navigator.

**Comment by afandria** [comment]
Any word on this?

I as looking into creating a Dialog (like the Fitness app does), and then I realized that the way that I needed to have a Navigator. I will probably want to structure my app with a Navigator in the long run, but I don't think we should be required to have one just to create a Dialog.

**Comment by abarth** [comment]
We've made some progress on this issue as part of fn3.  Now rather than subclassing `App`, just build an `App` component that has all the navigator features composed in:

https://github.com/flutter/engine/blob/master/examples/stocks/lib/main.dart#L74

Depending on your app, you might be able to just `runApp` the `App` component directly:

https://github.com/flutter/engine/blob/master/examples/widgets/navigation.dart#L60

We should get your app converted to fn3 and then see whether you're happy with what we've done here.

**Comment by Hixie** [comment]
Going by the list in the first comment, the only thing that's still annoying really is that we have to shuttle a reference to the NavigatorState back and forth.

**Comment by abarth** [comment]
Maybe `showDialog` should take a `BuildContext` instead of a `NavigatorState` and use the context to find the navigator...

**Comment by Hixie** [comment]
Yeah, we should do that everywhere rather than passing NavigatorStates all the time.

**Comment by collinjackson** [comment]
Agree, that would be a nice improvement

**Comment by abarth** [comment]
We now take a `BuildContext` instead of a navigator or `showDialog` and friends.
