### ISSUE TITLE
Many of our components draw outside their paintBounds

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#26]
_From @Hixie on July 14, 2015 17:22_

You can now easily tell what components paint outside their bounds by turning on debugPaintBoundsEnabled in sdk/lib/base/debug.dart. I noticed at least the following in the stocks app:

 - radio buttons
 - switches
 - anything with shadows, including drawer, popup menu, toolbar, floating action button, dialog
 - circles in the stock row

/cc @collinjackson @iansf 

_Copied from original issue: domokit/mojo#321_

**Comment by Hixie** [comment]
@abarth Any update on whether we are going to drop the paintBounds concept?

**Comment by abarth** [comment]
We can remove paintBounds.  There's some chance we'll need it later, but if that happens we can add it back.  We should still make most things paint in bounds so they'll hit test and clip correctly.
