### ISSUE TITLE
Pointer gesture is dropped if target widget hierchy changes

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#29]
_From @HansMuller on July 8, 2015 23:45_

A Listener that specifies onPointerDown, onPointerMove, onPointerUp should see all three events if
the PointerDown event targets its widget.

Currently if the target widget's hierarchy changes in response to PointerDown, the rest of the Pointer move/up gesture is dropped.

_Copied from original issue: domokit/mojo#312_

**Comment by Hixie** [comment]
This will become moot once the Gesture objects capture the pointers.

**Comment by abarth** [comment]
Gesture objects now capture the pointer
