### ISSUE TITLE
VariableHeightScrollable should be harder to construct improperly

### ISSUE THREAD

**Issue by tonygentilcore** [flutter/engine#295]
When creating a `VariableHeightScrollable`, I assumed the `layoutState` parameter was optional. Turns out if you don't pass one, you get a pretty uninformative stack:
```
E/chromium(14079): NoSuchMethodError: method not found: '_dirty'
E/chromium(14079): Receiver: null
E/chromium(14079): Arguments: []
E/chromium(14079): Stack Trace:
E/chromium(14079): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
E/chromium(14079): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
E/chromium(14079): #2      BlockViewport.syncRenderObject (http://127.0.0.1:9998/packages/sky/widgets/block_viewport.dart:175:21)
E/chromium(14079): #3      RenderObjectWrapper._sync (http://127.0.0.1:9998/packages/sky/widgets/widget.dart:723:5)
...
```

It'd be nice if the ctor either asserted that the value wasn't null or provided a reasonable default.

**Comment by abarth** [comment]
/cc @HansMuller 

In the code review, we talked about VariableHeightScrollable creating its own layoutState if the caller passed null.  It seems like that would help in this case.

@tonygentilcore We need to get you running in checked mode.  I suspect that would have given you a better error message because of this assert: https://github.com/domokit/sky_engine/blob/master/sky/packages/sky/lib/widgets/variable_height_scrollable.dart#L32

**Comment by tonygentilcore** [comment]
Thanks for pointing out that assert. I think just the presence of that is enough to close this bug if you like.

There have been a lot of nice updates in the mojo+dart+sky toolchain lately, so I hope I'm close to checked mode, but I think I'm blocked from being able to roll anything until the next sky release (because of that ABI breakage).

**Comment by abarth** [comment]
Do you have a plan to turn on checked mode in Sky?  If not, I can add a mojo arg to sky_viewer to do that.

**Comment by tonygentilcore** [comment]
#22 is filed for it, but I don't have anything in progress.

**Comment by abarth** [comment]
Working on it in #366

**Comment by abarth** [comment]
Now that we have checked mode plumbed through, I believe we can close this bug.
