### ISSUE TITLE
Maps support

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#30]
_From @collinjackson on July 8, 2015 20:23_

We are going to want to have support for maps in Sky.

There are a few ways we might go about doing this:
1. Use native maps widget for each platform to render the map
2. Use maps widget for each platform to render to a texture and draw the map ourselves
3. Develop a custom maps SDK for Sky

The second option would be ideal but may not be possible. We should investigate which approach is best and build a demo app.

_Copied from original issue: domokit/mojo#310_

**Comment by eseidelGoogle** [comment]
We might need this for the Fitness app, depending.
