### ISSUE TITLE
Hide SkyShell.app from dock when running as part of test_sky

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/engine#316]
This appears to be how:
http://stackoverflow.com/questions/1082374/making-a-checkbox-toggle-the-dock-icon-on-and-off

Chromium's ContentShell may already have a solution for this, @dpranke would know.

**Comment by dpranke** [comment]
Content Shell appears in the dock when we run the tests.

Back in the day, DRT didn't, but the code was quite different and more headless IIRC.
