### ISSUE TITLE
Stocks app everything is awesome checkbox changes without waiting for validation from the popup when you touch it directly

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#33]
_From @iansf on July 7, 2015 22:21_

Touching the "Everything is awesome" text correctly waits for validation from the popup, though.

_Copied from original issue: domokit/mojo#305_

**Comment by collinjackson** [comment]
I believe that this will get easier once we have the gesture recognizers that can negotiate for ownership over the tap event.

**Comment by eseidelGoogle** [comment]
I think this is the same as https://github.com/domokit/sky_engine/issues/42  Can we close one of them?
