### ISSUE TITLE
skyanalyzer does not report warnings

### ISSUE THREAD

**Issue by HansMuller** [flutter/engine#332]
It doesn't report anything unless with dartanalyzer process returns non-zero.  That only happens if dartanalyzer finds an error.

**Comment by abarth** [comment]
Looks like this is fixed by #333

**Comment by eseidelGoogle** [comment]
It was a partial fix. This was for followup

**Comment by abarth** [comment]
What more is there to do here?  It's unclear how to take action on this bug.

**Comment by HansMuller** [comment]
This issue comes from a different epoch. I don't think it's relevant anymore.
