### ISSUE TITLE
10776kb of apk is libsky_shell.so

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#357]
From #134:

10776 /usr/local/google/home/zra/Scratch/SkyDemo.apk/lib/armeabi-v7a/libsky_shell.so

Would be great to know how this breaks down, so we can get rid of any dead wood involved.

**Comment by eseidelGoogle** [comment]
I believe @abarth discovered we were shipping an uncompressed .so due to changes in Chromium's build system which we accidentally picked up.

**Comment by Hixie** [comment]
I thought that was just the assets. Also surely the APK is  a zip file and thus compressed anyway?

In any case, the uncompressed size matters too. That's what gets mapped into RAM, e.g..

**Comment by abarth** [comment]
It was assets.  We should be able to cut down the size of libsky_shell.so.

**Comment by abarth** [comment]
We can save 2.6 MB by not linking in Observatory in production.

**Comment by collinjackson** [comment]
Can this issue be closed?

**Comment by abarth** [comment]
Yes.
