### ISSUE TITLE
Change `sky_tool` to a bin/sky_tool.dart script?

### ISSUE THREAD

**Issue by devoncarew** [flutter/engine#362]
`sky_tool` is currently written in python and depends on pub creating `packages` directories. SDK 1.13 will no longer create packages directories and will instead create a `.packages` file. At this point the instructions on the getting started doc will stop working (running `./packages/sky/sky_tool start` to push the app to your device).

As there's already a bin/init.dart script (`pub run sky:init`), there should probably be a sibling sky_tool.dart or sky.dart script, which would handle pushing the app to the device.

**Comment by sethladd** [comment]
cc @pietergreyling

**Comment by abarth** [comment]
Yeah, there are several reason to rewrite sky_tool in dart.  We'll probably add it to the sky_tools package:
https://github.com/domokit/sky_tools

**Comment by abarth** [comment]
Done.  The script is `pub run flutter`.
