### ISSUE TITLE
Material Design: Indeterminate circular activity indicator

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#37]
_From @tonygentilcore on July 7, 2015 2:55_

It'd be useful to have the indeterminate circular activity indicator described here:
http://www.google.com/design/spec/components/progress-activity.html#progress-activity-types-of-indicators

/cc @collinjackson 

_Copied from original issue: domokit/mojo#295_

**Comment by eseidelGoogle** [comment]
Fitness app wants this too during data load.

**Comment by HansMuller** [comment]
If no one else has already started this, I'll build it.

**Comment by abarth** [comment]
We have this widget now.  It's not perfect, but we can close this bug and iterate on it in another bug.
