### ISSUE TITLE
Tapping the checkbox in settings shows the dialog but makes the change anyway

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#42]
_From @Hixie on June 29, 2015 19:23_

@collinjackson 

_Copied from original issue: domokit/mojo#281_

**Comment by Hixie** [comment]
Collin and I discussed this. We should fix this when we fix the gesture system to have gesture negotiation. The menu item and the checkbox would both try to get a tap, and only one would win.

**Comment by jamesr** [comment]
https://github.com/domokit/sky_engine/pull/436 addressed this bug in a slightly different way at @abarth's suggestion.
