### ISSUE TITLE
demo_launcher scrolling slow on Galaxy S5

### ISSUE THREAD

**Issue by spierce7** [flutter/engine#423]
I've been closely following this project. At the Dart Summit talk, very high performance numbers were shown. When I load the sample app from the play store onto my Galaxy S5, or any of my co-workers devices I see fairly low frame rate. The frame rate is consistent, but it looks to only be around 15-20 fps. (The asteroids game sample appears to have very good frame rate though).

Do the original performance aspirations of 120 fps still seem feasible? Does the team feel there are optimizations that can be done to the current engine to increase the current performance significantly?

**Comment by abarth** [comment]
> Do the original performance aspirations of 120 fps still seem feasible?

Yes.

> Does the team feel there are optimizations that can be done to the current engine to increase the current performance significantly?

Yes.  Currently we are drawing every pixel of every frame from scratch.  We'll eventually cache some pixels and re-use them from previous frames.  We're purposefully waiting to add caching to the graphics pipeline because we want to see how far we can push the system in its current configuration.

**Comment by abarth** [comment]
c7f9c68a873dc680f5483f4f157d8091f97f425b should improve scrolling performance on the demo_launcher by 3x.  We'll need to check an S5 with the next release of SkyDemo to see if that fixes this issue.

**Comment by abarth** [comment]
I believe we scroll much faster than when this issue was filed, so I'm going to mark this issue as fixed.  Thanks!

**Comment by spierce7** [comment]
@abarth You can keep this closed if you want, but scrolling is still pretty laggy on the stock sample with the samsung s5, and also the nexus 5x I just tried it with too. After a while it seems to smooth out, but it takes some time.

**Comment by abarth** [comment]
Ok, I've re-opened this issue.
