### ISSUE TITLE
sky.Image is backed by SkBitmap (deprecated) instead of SkImage

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#43]
_From @vlidholt on June 23, 2015 21:28_

In the bindings layer the sky.Image is backed by SkBitmap instead of SkImage. SkImage is a newer API and offer optimizations that aren't available through SkBitmap.

_Copied from original issue: domokit/mojo#265_

**Comment by Hixie** [comment]
_From @collinjackson on June 23, 2015 21:33_

The decoding happens in https://github.com/domokit/mojo/blob/master/sky/engine/core/loader/CanvasImageDecoder.cpp

Right now we're calling decoder->frameBufferAtIndex(0)->getSkBitmap()

If there is an easy way to get an SkImage instead that would be great

**Comment by Hixie** [comment]
_From @reed-at-google on June 23, 2015 21:40_

If I make modifications to the imagedecoders, should that be directly here, or if they are updated in chromium/blink, will those changes be "merged" back into mojo?

**Comment by Hixie** [comment]
_From @collinjackson on June 23, 2015 21:43_

That is a good question for @abarth or @eseidel

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 23, 2015 22:19_

We are completely forked from Blink. :)  We don't merge anything from Blink.  The mojo project occasionally merges a couple directories from Chromium:
https://github.com/domokit/mojo/wiki/Directory-guide

**Comment by abarth** [comment]
We now use SkImage.
