### ISSUE TITLE
Some links in the readme for the sky package on pub.dartlang do not work

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#44]
_From @keertip on June 25, 2015 0:17_

The readme for the published sky package has links to `framework`, `widgets tutorial`, `examples directory` for more information on sky. These links do not work. 

_Copied from original issue: domokit/mojo#271_

**Comment by Hixie** [comment]
_From @abarth on June 25, 2015 18:21_

Maybe the pub.dartlang docs for Sky should just point to https://github.com/domokit/sky_sdk/blob/master/README.md ?

**Comment by abarth** [comment]
These should be fixed now that we host everything on flutter.io.
