### ISSUE TITLE
Sky Demo on Nexus 6, Swipe Away, no arrows, under-label not centered

### ISSUE THREAD

**Issue by HansMuller** [flutter/engine#458]
Running the card_collection.dart demo on a Nexus 6. When a card dragged the blue label underneath should be centered and left/right arrows should appear on the left and right edges.

**Comment by HansMuller** [comment]
https://github.com/domokit/sky_engine/pull/472 Fixes the text centering problem (and eliminates double-dismiss for fast thumbs).

**Comment by abarth** [comment]
I guess that means this issue is fixed?

**Comment by HansMuller** [comment]
Yes, thanks for closing this issue.
