### ISSUE TITLE
Missing bindings for SkPaint and SkCanvas

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#47]
_From @vlidholt on June 23, 2015 16:41_

Many drawing methods are missing in Dart for SkPaint and SkCanvas.

_Copied from original issue: domokit/mojo#261_

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 23, 2015 17:4_

They're pretty simple to add:
https://github.com/domokit/mojo/blob/master/sky/engine/core/painting/Canvas.idl

**Comment by Hixie** [comment]
_From @abarth on July 6, 2015 16:10_

Would you be willing to file individual bugs for the specific things that need to be added?

**Comment by abarth** [comment]
This issue is too open ended.  Please file separate bugs for individual feature you'd like added.
