### ISSUE TITLE
SkyShell should exist on Mac

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#49]
_From @eseidelGoogle on June 22, 2015 23:27_

This would make it possible for us to be able to run test on a Mac.

This should be possible now after the recent refactorings of SkyShell for ios.

@chinmaygarde @collinjackson @johnmccutchan 

_Copied from original issue: domokit/mojo#258_

**Comment by Hixie** [comment]
_From @tonygentilcore on June 23, 2015 9:6_

Is there a strong reason this shouldn't be done in the context of mojo shell instead of sky shell?

/cc @qsr

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 23, 2015 16:6_

If we had a mojo_shell on mac, we could use it.  But sky_shell is much less code to port and would serve our immediate needs.

**Comment by Hixie** [comment]
_From @tonygentilcore on July 6, 2015 23:56_

I thought @jamesr was carrying a hacky patch in his client at one point in time that allowed mojo shell to be built on a mac and it didn't seem like tremendous amounts of work. Maybe I misunderstood or misremembered.

Just for my information, would you be willing to expound on the additional code that has to be ported for mojo shell to work on mac? I'd really like to be able to have the same nice developer experience for Mojo that Sky enjoys :)

**Comment by Hixie** [comment]
_From @eseidelGoogle on July 7, 2015 1:6_

If he does I'd love to see it.  Bringing up sky_shell on mac now.

**Comment by Hixie** [comment]
_From @viettrungluu-cr on July 7, 2015 16:50_

Sure, it's currently trivial to get mojo_shell building/running on a Mac.
But you'd be very disappointed when you realized that there's no native
viewport service, which would be a huge amount of work to get running. (And
as we make mojo_shell more interesting, e.g., by adding sandboxing, it'd
become more and more of a burden to support Mac.)

**Comment by eseidelGoogle** [comment]
I think @chinmaygarde is nearly done with this.

**Comment by abarth** [comment]
SkyShell exists on mac now.
