### ISSUE TITLE
SkyDemo.apk crashes on the Moto E

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/engine#5]
The Crash is inside Skia when clicking on the "Cards" example in SkyDemo.apk.

http://pastebin.com/Z5JqVZ6L

**Comment by eseidelGoogle** [comment]
.sky.demo/org.domokit.sky.demo.SkyDemoActivity: 18:61)* (SurfaceView: 18:360) (SurfaceView: 1:2)* (org.domokit.sky.demo/org.domokit.sky.demo.SkyDemoActivity: 1:5)*
D/dalvikvm( 8584): GC_CONCURRENT freed 3030K, 71% free 3231K/11024K, paused 1ms+1ms, total 31ms
I/chromium( 8584): [INFO:GrGLProgramBuilder.cpp(460)] --From Vertex Shader:
I/chromium( 8584): --From Fragment Shader:
I/chromium( 8584):
I/chromium( 8584): [INFO:GrGLProgramBuilder.cpp(462)] ../../third_party/skia/src/gpu/gl/builders/GrGLProgramBuilder.cpp:462: failed assertion "false && "Error linking program""
I/chromium( 8584):
F/chromium( 8584): [FATAL:GrGLProgramBuilder.cpp(462)] SK_CRASH

**Comment by eseidelGoogle** [comment]
Here is the full adb logcat with g_printShaders enabled:
http://pastebin.com/WKWtXcXr

**Comment by eseidel** [comment]
I'll be sure to test this again next week.

**Comment by abarth** [comment]
We fixed this when we switched to having Skia build the GL table.
