### ISSUE TITLE
RenderClipOval should have better hit testing

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#53]
_From @abarth on June 18, 2015 15:50_

Currently if you tap outside the oval, RenderClipOval will still think you hit it.  Instead, we should compare the hit location against the shape of the oval.

_Copied from original issue: domokit/mojo#252_

**Comment by Hixie** [comment]
@abarth I seem to remember discussing this issue, and concluding that this affected many classes. But I can't find any record of that discussion.

Looking through our rendering classes, I'm guessing it boils down to this:
- [ ] `RenderClipOval` should honour the clip
- [ ] `RenderDecoratedBox` should honour the shape and border radius
- [ ] `ClipRRect` should honour the radius

**Comment by abarth** [comment]
There are some deeper questions:
* Should opacity defer to its child for hit testing?
* If you have a Flex with some free space, should you be able to hit the flex if you test in some of the free space?
* Should all render objects that paint only their children defer to their children for hit testing?
