### ISSUE TITLE
Sky Demo fails to launch sample apps if launched using Sky Shell (e.g., with sky_tool) and SkyDemo.apk is not installed

### ISSUE THREAD

**Issue by iansf** [flutter/engine#531]
Sky Demo depends on SkyDemoActivity being available to receive an intent, but Sky Shell does not have SkyDemoActivity.

Attempting to launch any of the demos gives this error:

I/ActivityManager(  737): START u0 {act=android.intent.action.VIEW dat=http://localhost:9888/game/lib/main.dart flg=0x8080000 cmp=org.domokit.sky.demo/.SkyDemoActivity (has extras)} from uid 10093 on display 0
E/ActivityImpl(22823): Unable to startActivity
E/ActivityImpl(22823): android.content.ActivityNotFoundException: Unable to find explicit activity class {org.domokit.sky.demo/org.domokit.sky.demo.SkyDemoActivity}; have you declared this activity in your AndroidManifest.xml?
E/ActivityImpl(22823): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1777)
E/ActivityImpl(22823): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
E/ActivityImpl(22823): 	at android.app.Activity.startActivityForResult(Activity.java:3745)
E/ActivityImpl(22823): 	at android.app.Activity.startActivityForResult(Activity.java:3706)
E/ActivityImpl(22823): 	at android.app.Activity.startActivity(Activity.java:4016)
E/ActivityImpl(22823): 	at android.app.Activity.startActivity(Activity.java:3984)
E/ActivityImpl(22823): 	at org.domokit.activity.ActivityImpl.startActivity(ActivityImpl.java:67)
E/ActivityImpl(22823): 	at org.chromium.mojom.activity.Activity_Internal$Stub.accept(Activity_Internal.java:132)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.RouterImpl.handleIncomingMessage(RouterImpl.java:235)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.RouterImpl.access$000(RouterImpl.java:18)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.RouterImpl$HandleIncomingMessageThunk.accept(RouterImpl.java:30)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.Connector.readAndDispatchMessage(Connector.java:245)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.Connector.readOutstandingMessages(Connector.java:204)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.Connector.onAsyncWaiterResult(Connector.java:170)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.Connector.access$100(Connector.java:25)
E/ActivityImpl(22823): 	at org.chromium.mojo.bindings.Connector$AsyncWaiterCallback.onResult(Connector.java:150)
E/ActivityImpl(22823): 	at org.chromium.mojo.system.impl.CoreImpl.onAsyncWaitResult(CoreImpl.java:560)
E/ActivityImpl(22823): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
E/ActivityImpl(22823): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
E/ActivityImpl(22823): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityImpl(22823): 	at android.os.Looper.loop(Looper.java:135)
E/ActivityImpl(22823): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/ActivityImpl(22823): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityImpl(22823): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityImpl(22823): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/ActivityImpl(22823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by eseidelGoogle** [comment]
This is related at least to https://github.com/domokit/sky_engine/issues/557

**Comment by abarth** [comment]
I'm not sure how we should address this issue.  Maybe demo_launcher shouldn't be an example we point people to?  It depends on SkyDemo.apk being installed to work because it itself is SkyDemo.apk...

**Comment by abarth** [comment]
We've removed SkyDemo.apk.
