### ISSUE TITLE
Sky framework needs URL routing

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#58]
_From @abarth on June 14, 2015 17:47_

Different screens inside a Sky application should be named using URLs.  When an app starts up with a given URL, the routing system should build the correct screen.  When some component deep in the app wants to change to a different screen, it should be able to do that by asking for the screen by its name.

_Copied from original issue: domokit/mojo#243_

**Comment by Hixie** [comment]
_From @collinjackson on June 24, 2015 17:58_

Screens can now be named with URLs. We don't have a mechanism for starting up a Sky application with a particular screen yet.

**Comment by abarth** [comment]
The remaining work here is covered in #776
