### ISSUE TITLE
Sky packages should be able to write unit tests that depend on Sky

### ISSUE THREAD

**Issue by collinjackson** [flutter/engine#580]
jackson-macpro:playfair jackson$ dart --version
Dart VM version: 1.11.0-dev.3.0 (Thu May 28 03:42:12 2015) on "macos_x64"

jackson-macpro:playfair jackson$ pub run test test/playfair_test.dart 
Wrong script snapshot version, expected '146df3da808a6da22679d25262d18cfb' found '6ab2a2a1aedc6faea804a9c1850edf4b'
00:00 +0 -1: loading test/playfair_test.dart                                                       
  Failed to load "test/playfair_test.dart":
  The built-in library 'dart:sky' is not available on the stand-alone VM.
  'package:playfair/playfair.dart': error: line 7 pos 1: library handler failed
  import 'dart:sky' as sky;
  ^
00:00 +0 -1: Some tests failed.                                                                    

If we included the Sky shell executable in the Sky package we could run these tests.

**Comment by eseidelGoogle** [comment]
Discussed this with @abarth.  There are several problems to solve here.

1.  We do not build Mac binaries for releases, currently.  We need a Mac VM in the cloud to do so.
2.  Once we build Mac binaries, we don't yet upload them to google storage (like we do linux and android-arm: https://github.com/domokit/sky_engine/blob/master/sky/tools/big_red_button.py#L63), but we could once we build them on every revision.
3.  Even once we have those binaries, we need to teach sky_tool (or more likely https://github.com/domokit/sky_tools @iansf) how to use them.  Presumably we'd have a `pub run sky_tools:unittest` executable or such @devoncarew.
