### ISSUE TITLE
Need support for charts in Sky

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#59]
_From @abarth on June 14, 2015 17:40_

Possibly something like https://github.com/google/charted

Presumably we don't want this in the main framework.  Charting support might be a good place to start with another Dart pub package that depends on the |sky| package.

_Copied from original issue: domokit/mojo#242_

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 22, 2015 23:47_

I briefly looked at this.  charted currently imports dart:html in many places and will take some surgery to remove that dependency. @psunkari

**Comment by abarth** [comment]
We now have a basic charting library in `playfair`.
