### ISSUE TITLE
Functions missing in sound API

### ISSUE THREAD

**Issue by vlidholt** [flutter/engine#611]
In order of priority:
- SoundTrack:s cannot be looped (needed for background music)
- There are no callbacks when SoundTrack:s complete
- SoundTrack:s cannot control the volume (would be required for fading/mixing different music tracks)
- SoundEffect:s should use Android's SoundPool classes instead of MediaPlayer (required for the following bullets)
- SoundEffect:s are missing looping, volume, pitch, and pan controls (required for positional audio)
- SoundEffectStream:s are not being properly deleted when finished playing and thus leaking memory
- SoundTrack:s are not being properly deleted when finished playing and thus leaking memory
- All other missing callbacks for SoundTrack and SoundEffect.

**Comment by eseidelGoogle** [comment]
Thank you! This is very helpful.

**Comment by vlidholt** [comment]
API here: https://github.com/vlidholt/sky_engine/blob/master/skysprites/lib/src/sound.dart
