### ISSUE TITLE
Add z-index to Stack

### ISSUE THREAD

**Issue by afandria** [flutter/engine#613]
When using a Stack Container, one normally positions each element (via Transform) to the correct position. The Stack always draws the children in-order. However, this creates a problem for Stack users; to display overlapping children properly, they must be sorted from bottom to top.

An alternative way (easier than sorting) would be to add the notion of a z-index local to the Stack. Elements would be bucketed into groups based on z-index, and then drawn.

This is helpful since it allows certain elements to draw themselves later if transient state dictates that it would be better to do so. (However, since this z-index doesn't cross Container boundaries, this proposal doesn't mean that a high z-index means 'always on top, everywhere'.)

**Comment by abarth** [comment]
A workaround for now is to reorder the children in the Stack when you want to change paint order.  We should make this easier by fixing this issue, however.  :)

**Comment by abarth** [comment]
I think we're going to leave sorting the Stack's children as the way to achieve this effect.  Please let me know if that causes a problem for your app.

**Comment by afandria** [comment]
I'll do my best with sorting the children. I originally wanted z-index for drag-and-drop. The new implementation covers that need. I may want this again with transitions, but I have yet to do much with those.
