### ISSUE TITLE
Sky Framework should use quiver.core for hashCodes

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#62]
_From @eseidelGoogle on June 12, 2015 1:28_

http://www.dartdocs.org/documentation/quiver/0.21.4/index.html#quiver/quiver-core

It's silly we write our own hashCodes by hand.

We'll need to add quiver to DEPS.

@johnmccutchan 

_Copied from original issue: domokit/mojo#236_

**Comment by Hixie** [comment]
_From @sethladd on June 12, 2015 4:19_

Cc @cbracken fyi

**Comment by Hixie** [comment]
_From @johnmccutchan on June 12, 2015 14:16_

https://codereview.chromium.org/1184753002/

Blocked on getting a mirror of quiver setup, which I pinged Robert about.

**Comment by eseidelGoogle** [comment]
We should no longer be blocked on mirrors.  We just use pub get to get all our packages which happen w/o mirroring, no? @abarth

**Comment by abarth** [comment]
Correct.
