### ISSUE TITLE
Add support android version 4.4

### ISSUE THREAD

**Issue by thinkwing** [flutter/engine#632]
Currently Sky requires an Android device running the Lollipop (or newer) version of the Android operating system, wish to add support version 4.4(or 4.1+)

**Comment by eseidel** [comment]
We definitely can (and should) support older versions of Android.  Part of the trouble is that we'll need to add a replacement for `adb reverse` which is new in lolipop's adb and allows forwarding ports from the device to the host.  Thankfully Chromium already wrote a replacement for adb reverse on older devices, we just need to build and use it: https://code.google.com/p/chromium/codesearch#chromium/src/tools/android/forwarder2/

See also https://github.com/domokit/sky_engine/issues/187

**Comment by jamesr** [comment]
Does adb reverse need device support? You can generally use a newer sdk to target older devices.

**Comment by eseidelGoogle** [comment]
My understanding is the adb server on the device comes from the system,
yes.

**Comment by abarth** [comment]
This is getting close, but there are a couple more steps.  :(

**Comment by abarth** [comment]
I've been testing a Jelly Bean device with the new --no-http option in the flutter tool and it seems to work.  Once we make --no-http the default, I'll lower the version check to down to API level 19.

**Comment by abarth** [comment]
Done in https://github.com/flutter/tools/commit/1a8f8f4ffa8e7c8bceff944733a443d2483b74fd

The next release of Flutter will include support down to Jelly Bean.
