### ISSUE TITLE
Calling scrollTo(offset, myAnimation) from a myAnimation status listener can fail

### ISSUE THREAD

**Issue by apwilson** [flutter/engine#645]

**Comment by HansMuller** [comment]
Calling Scrollable.scrollTo(newOffset, myToOffsetAnimation) stops the current toOffset animation (if any) and then configures and plays myToOffsetAnimation. If the toOffset animation runs to completion, then an AnimationStatus.completed status listener installed by the Scrollable resets the Scrollable's toOffset related internal state.  If a scrollTo() call happens from one of the current toOffset animation's AnimationStatus.completed status listeners, and the Scrollable's status listener runs later, it will end up resetting the new animation's state, not the old one.
