### ISSUE TITLE
Windows support (development host only, not deployment target)

### ISSUE THREAD

**Issue by Scorpiion** [flutter/engine#771]
I understand that Windows support is not prio 1 atm, but in the future, as a platform for developing Android apps (and maybe iOS apps), would it be possible to add Windows support? I understand that it would be some work, but basically what I'm asking is if it's part of the long term plan or simply ignored on purpose for some reason (other than maybe no devs on the team are using Windows..).

Even if I myself only use Linux (close to 10 years Linux only) I think it can be good for the project to support Windows in the long run, at Stackoverflow's latest developer survey Windows developers was still a little bit more that 50% (Mac and Linux at ~21% each): 
http://stackoverflow.com/research/developer-survey-2015#tech-os

The only reference of Windows I could find was this old comment in an old readme:
https://github.com/domokit/sky_engine/pull/165/files#r35055666

_And just to be extra clear and avoid any confusion, this issue is about developing Android and iOS apps on Windows, not deploying Sky to Windows Phone._

**Comment by sethladd** [comment]
To be clear, are you asking to deploy to windows phone, windows desktop, or
simply develop on windows?

**Comment by Scorpiion** [comment]
Hi @sethladd, _"simply develop on windows"_, yes.

**Comment by eseidel** [comment]
Yup.  We can definitely support windows development at some point in the future.  Just focused on polishing the actual deployed product first.  If the product isn't first awesome, it doesn't matter what development environments it supports. :)

**Comment by sethladd** [comment]
Thanks! Agreed... there are a ton of Windows developers.

**Comment by Scorpiion** [comment]
Thanks for the reply @eseidel, sounds great, I think the team have the right focus, looking forward to that initial awesome product! :+1:
