### ISSUE TITLE
Drawer should open using swipe-from-side

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#79]
_From @eseidelGoogle on June 10, 2015 18:27_

Code is here:
https://github.com/domokit/mojo/blob/master/sky/sdk/lib/framework/components2/drawer.dart

_Copied from original issue: domokit/mojo#232_

**Comment by jgw96** [comment]
Has this been implemented in the latest version of the demo app?

**Comment by abarth** [comment]
Not yet.
