### ISSUE TITLE
Design a more rational Sky text styling/layout/rendering API

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#80]
_From @Hixie on June 9, 2015 21:14_

_Copied from original issue: domokit/mojo#227_

**Comment by Hixie** [comment]
@eseidelGoogle This issue is tracking everything around the LayoutRoot stuff, including dropping Document.

**Comment by Hixie** [comment]
I've been thinking about this, but before I can make much progress on actually doing anything about it I'll first need to delete a lot more C++ code.

Things I think we need to keep supporting:
- All the CSS properties that the inline code already supports
- Bidi, glyph shaping, etc
- Painting Selections in a host-platform-friendly way
- Describing selections, probably using the Range API
- Easy mutations of the tree, probably including Range mutations

Things I think we need to do:
- [ ] Convert the CSS API from a string-based API to a real Dart binding
- [ ] Add support for non-alphabetic baselines (see #46)
- [ ] Accessibility and Indexability for text
- [ ] Inter-glyph hit testing
- [ ] Inter-glyph position reporting (for caret painting)

Much of the remainder should probably go.

**Comment by Hixie** [comment]
@abarth did we lose "Painting Selections in a host-platform-friendly way" in the recent massacre?

I think "Accessibility and Indexability for text" probably needs to happen at the Dart layer. The rest is covered by #1774.

**Comment by abarth** [comment]
The C++ code no longer knows how to describe or paint selections.  Previously, the selection state was held on the DOM side and expressed in terms of DOM ranges.  If we want this in C++, we'll need a different data model based on render objects.

In the web, ranges don't have to be subtrees, unlike other text spans, like bold or italics.  We might want to consider unifying the selection machinery with the inline formatting machinery.

**Comment by Hixie** [comment]
We can probably do it from Dart, if we have all the metrics discussed in #1774.

**Comment by Hixie** [comment]
Filed #1778 for text selections. This bug is entirely subsumed by others now, so closing.
