### ISSUE TITLE
NetworkImage occasionally does not grab the image

### ISSUE THREAD

**Issue by afandria** [flutter/engine#801]
Unfortunately, I haven't been able to consistently reproduce it, but I do see it often.

I will attempt to grab a stack trace the next time I see it.

**Comment by afandria** [comment]
Unfortunately, adb logcat doesn't reveal anything on its own for me. I added a print out to image_cache.dart, but the missing image was successfully downloaded (statusCode: 200).

```
I/sky     (14098): UrlResponse(error: null, body: MojoDataPipeConsumer(handle: MojoHandle(h: 1168, status: MojoWaitResult(result: OK, state: (Readable, PeerClosed))), status: OK, available: 238), statusCode: 200, url: http://localhost:9888/lib/classic/down/hj.png, statusLine: OK, headers: [HttpHeader(name: content-type, value: image/png), HttpHeader(name: last-modified, value: Tue, 25 Aug 2015 18:13:38 GMT), HttpHeader(name: cache-control, value: no-store), HttpHeader(name: date, value: Wed, 26 Aug 2015 01:16:31 GMT), HttpHeader(name: server, value: dart:io with Shelf), HttpHeader(name: content-length, value: 238), HttpHeader(name: OkHttp-Selected-Protocol, value: http/1.1), HttpHeader(name: OkHttp-Sent-Millis, value: 1440551787552), HttpHeader(name: OkHttp-Received-Millis, value: 1440551787556)], mimeType: image/png, charset: null, redirectMethod: null, redirectUrl: null, redirectReferrer: null)
```

If this is true, this this implies that the image was not successfully decoded: In `image_cache.dart`, `new sky.ImageDecoder(response.body.handle.h, completer.complete);` fails to call the callback to complete the future.

To confirm this further, I put a printout statement only for the success cases of image_cache.dart, when it would attempt to send it to the sky image decoder. `adb logcat` produced the following for URLs of fetched images:

```
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/d5.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/d4.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/d3.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/d2.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/d1.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/ck.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/cq.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/cj.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/c10.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/down/c9.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c8.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c7.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c6.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c5.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c4.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c3.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c2.png
I/sky     (15714): Decoding (http://localhost:9888/lib/classic/up/c1.png
```

My example puts 8 cards on the first row, 5 on the second, 4 on the third, and 1 on the last. But the 3rd row is missing it's 2nd card. The cards were not shuffled, so that means the 2 of Diamonds is missing.

![screenshot_2015-08-25-18-27-30](https://cloud.githubusercontent.com/assets/2432033/9483645/1619bf78-4b57-11e5-84de-f160fe166f34.png)

In this particular run, despite the request for `http://localhost:9888/lib/classic/down/d2.png` succeeding, it failed to render, so I think the ImageDecoder did not call its callback.

**Comment by abarth** [comment]
Curious if this is still happening after the fn3 conversion.

**Comment by afandria** [comment]
Yes, it is still happening, unfortunately.

**Comment by abarth** [comment]
I have a theory about what's going on.  I think the `ImageDecoder` is getting garbage collected while the decode callback is in flight.
