### ISSUE TITLE
Material Design: Tabs

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#82]
_From @eseidelGoogle on June 8, 2015 21:8_

Our next demo will need a Material Design Tab:
http://www.google.com/design/spec/components/tabs.html

The Android ones appear to go off-screen, even for small numbers of tabs.  Unclear which tab-spacing we'll want to implement.

_Copied from original issue: domokit/mojo#223_

**Comment by Hixie** [comment]
_From @eseidelGoogle on June 29, 2015 21:5_

I heard mention in the standup that tab navigation worked?

**Comment by Hixie** [comment]
_From @HansMuller on June 30, 2015 14:33_

As of https://codereview.chromium.org/1212993003, basic support for not-scrollable tabs is in. There's a
simple demo in sky/sdk/example/widgets/tabs.dart.

Support for scrollable tabs is next. And then support for animating selected tab transitions.

**Comment by abarth** [comment]
We now have tabs.
