### ISSUE TITLE
examples/widgets/mixed_viewport.dart crashes when you remove big nodes before small nodes

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#820]
To reproduce:
- click add a few times until you have a big block followed by a small block
- scroll the big block almost off screen, such that more of the block is off the top of the screen than the height of the small block
- tap the big block

The small block is moved off the screen and then there's a crash.

CC @HansMuller

**Comment by Hixie** [comment]
I think you can also trigger this in examples/widgets/card_collection.dart by flinging a card out while scrolling.

**Comment by HansMuller** [comment]
I have looked into this (without success) more than once.  The failure is signalled by this assert:

'http://localhost:9888/packages/sky/widgets/framework.dart': Failed assertion: line 366 pos 14: 'oldNode.mounted' is not true.

The problem can be avoided by changing MixedViewport._doLayout():
```
    // Remove any old children.
    for (_Key oldChildKey in childrenByKey.keys) {
      if (!childrenByKey[oldChildKey].mounted)  // HACK
        continue;
      ...
     }
```
It's not clear how a !mounted Widget ends up in childrenByKey at this point.

**Comment by HansMuller** [comment]
I've checked this against the original test case and with the card_collection.dart (swipe away) demo. The bug appears to have been fixed. I haven't been able to pin down exactly which change gets the credit.
