### ISSUE TITLE
Following CONTRIBUTING.md broken

### ISSUE THREAD

**Issue by alhaad** [flutter/engine#843]
Following CONTRIBUTING.md to the word did not work for me.
Simply doing `gclient sync` was failing with:
```
________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress git@github.com:domokit/sky_engine.git /usr/local/google/home/alhaad/sky_engine/_gclient_src_wqGjeD' in '/usr/local/google/home/alhaad/sky_engine'
[0:00:03] Cloning into '/usr/local/google/home/alhaad/sky_engine/_gclient_src_wqGjeD'...
[0:00:04] Permission denied (publickey).
[0:00:04] 
[0:00:04] fatal: Could not read from remote repository.
[0:00:04] 
[0:00:04] Please make sure you have the correct access rights
[0:00:04] and the repository exists.
----------------------------------------
```

I had to manually clone the repo to get it working.

**Comment by jamesr** [comment]
What url did you clone from?

**Comment by alhaad** [comment]
Using the https url works. But the instructions need to be updated, I think.

**Comment by jamesr** [comment]
The instructions say to set the git url up to be:

"url": "git@github.com:<your_name_here>/sky_engine.git",

did you replace <your_name_here> with 'domokit'?  That won't work, but if you make a github fork of sky it should work.

**Comment by jamesr** [comment]
err, markdown ate my angle brackets. here's what I mean:

https://raw.githubusercontent.com/domokit/sky_engine/master/CONTRIBUTING.md line 24

**Comment by abarth** [comment]
This should be fixed now that we've added instructions for configuring your GitHub private keys.
