### ISSUE TITLE
Border code should use Skia dedicated border APIs

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#89]
_From @Hixie on June 4, 2015 0:27_

_Copied from original issue: domokit/mojo#196_

**Comment by abarth** [comment]
We now use strokes for uniform borders.  Skia doesn't support non-uniform borders...  I'm not sure what more needs to be done for this bug.

**Comment by Hixie** [comment]
IIRC, this was originally filed to handle backgrounds and borders with a single paint call so that you wouldn't get artifacts if you painted semi-transparent borders with a background.
