### ISSUE TITLE
No way to listen for every scrollend

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/engine#906]
A symptom of this is that PagableList right now doesn't call its PageChangedCallback or (or even settle) at the end of scrollTo intiated scrolls (such as done by ensureWidgetIsVisible).  The web has events for scrollstart, scrollupdate and scrollend.  We probably want events as well, but certainly subclasses want the ability to hook into and add scrollend or scrollstart behavior.

@HansMuller

**Comment by abarth** [comment]
We have `onScrollEnd` now.
