### ISSUE TITLE
EditableString onUpdated() callback doesn't run when you hit the CR key

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#93]
_From @HansMuller on May 22, 2015 17:22_

I was hoping to see a newline appended to the text.

_Copied from original issue: domokit/mojo#175_

**Comment by Hixie** [comment]
_From @abarth on May 26, 2015 14:11_

Feel free to steal from me.  Just assigning to myself to make sure I don't lose track of it.

Rather than calling onUpdated, we should probably add another callback that gets called for CR.

**Comment by jason-simmons** [comment]
Added an Input.onSubmitted callback
