### ISSUE TITLE
Widget for changing layout based on rotating device

### ISSUE THREAD

**Issue by Hixie** [flutter/engine#963]
We should have a Widget that takes two build functions as constructor arguments and calls one or the other based on whether the aspect ratio it is to be laid out in is horizontal or vertical.

Maybe this should be a layout callback case.

Ideally this would be written is such a way as to be ready to handle iOS-style rotation animations.

**Comment by abarth** [comment]
We have MediaQuery now.  Is that sufficient or is more work needed here?  /cc @collinjackson
