### ISSUE TITLE
Get rid of sky_server and use skyx on all platforms

### ISSUE THREAD

**Issue by iansf** [flutter/engine#983]
We currently use sky_server for Android development and skyx for iOS development.  sky_server has some nice properties, but it can cause a lot of confusion when switching between projects.  Unifying behind skyx and making that experience as fast as possible is the current approach.

**Comment by abarth** [comment]
I have this half-working locally.

**Comment by abarth** [comment]
This is now available for testing using the --no-http option.

**Comment by abarth** [comment]
This option is now the default.
